### ISSUE TITLE
Copy, Paste hotkeys do not work

### ISSUE THREAD

**Issue by ivan-vasilich** [giuspen/cherrytree#802] opened 2020-05-13 08:59 UTC
Sorry for the bad English, I use google translator (I am Russian)

CherryTree is an excellent product. Thanks to the developers.

But my keyboard shortcuts do not work (copy and paste, like plain text), and it poisons my life. Please, help.

I have Windows 7, I started working with CherryTree 0.39.2. Updated, now CherryTree 0.39.3. The problem has not disappeared.

I did a lot of experiments and got such a result.

For simplicity, I replaced, set up these shortcuts:
- Copy as plain text "Ctrl + C"
- Paste as plain text "Ctrl + V"

This procedure makes hotkeys work:
1. Move the mouse marker to the CherryTree sheet
2. Switch from RU to EN keyboard case
3. Select any text on the sheet and use the right mouse button to make “Copy”, then “Paste”.
4. After that, the hot keys work in any register.

Further, during operation, the hot keys will stop working if you use the function with the right mouse button, for example, "Cut", "Copy". In order for the hot keys to work again, you need to repeat steps 2, 3, 4.

**Comment by txe** [comment] 2020-05-13 10:31
Yeah, I can reproduce this issue,
I believe, it is related to gtk2 (it's too old) and there is no such issue on gtk3 which is coming soon.
You need to wait a bit, @giuspen is working on gtk3 version installer for windows.

**Comment by txe** [comment] 2020-06-18 21:21
Closing this issue because it is not possible to be fixed for win/pygtk,
C++ 0.99 version can be downloaded from https://www.giuspen.com/cherrytree/#downl (see at the end of the block)

**Closed by txe** 2020-06-18 21:21 UTC
Labels: os: win, topic: clipboard, usability
