### ISSUE TITLE
Undo causes unexpected formatting errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#23] opened 2015-03-22 22:19 UTC
```
What steps will reproduce the problem?
1. Create a a node with any amount of text. Apply different rich-text formats 
to discrete portions of the text, such as bolding some words, highlighting 
others, adding bullet lists, underlines, etc.
2. Use ctrl+z or Undo command to revert some of these changes, and observe that 
the rich-text formatting gets distrupted (e.g., a whole section might now 
become unerlined).

What version of the product are you using? On what operating system?

Using cherytree version 0.35.6 with Ubuntu 14.10 64-bit.

```

Original issue reported on code.google.com by `leonardo...@gmail.com` on 5 Jan 2015 at 3:17

**Comment by Bystroushaak** [comment] 2015-08-16 01:10
I can confirm this.

**Comment by Bystroushaak** [comment] 2015-10-11 15:16
Okay. Today I encountered the bug twice and it is pretty annoying.

This is really bad bug, because it cannot be easily reproduced and presents itself only when you have large amounts of formatted text. For me, it usually presents, when I have italic and monospace fonts. Then when I press ctrl+z, the random surrounding sections gets tagged as italic/monospace.

Pressing additional ctrl+z doesn't help, you have to exit cherrytree.

Now I have one node where it can be demonstrated, so I will make a video.

**Comment by Bystroushaak** [comment] 2015-10-11 15:52
Here is the file with exported article, so you can try it yourself:

- http://kitakitsune.org/bhole/example.ctd

And here is promised video:

- http://kitakitsune.org/bhole/example.webm

**Comment by giuspen** [comment] 2015-10-15 21:41
Hi, I'm sorry but I'm not understanding from the video, could you describe
textually? Also I see that you have the spell check active, do you have the
same issue with and without spell check?

**Comment by Bystroushaak** [comment] 2015-10-16 14:35
I have this file with some formating. There are HTML links, italic text, headings, maybe bold, underlined or strikethrough text. Standard stuff.

Now, I edit the file somewhere near the end and I decide to revert the change by using undo (in the video, that happens from the menu, normally I would press CTRL+u). As you can see in the video, after I do the undo, not only that the last change was reverted, but there is now large section of formatted italic text, which I didn't created. What happened was that some random italic section overflowed all the way to the next italic section.

**Comment by Bystroushaak** [comment] 2015-10-16 14:37
Here is the text before change:

![snimek obrazovky-example ctd - -home-bystrousak-plocha - cherrytree 0 35 11](https://cloud.githubusercontent.com/assets/227282/10544500/085352dc-7424-11e5-8edf-2300ca896b7b.png)

Here after the undo:

![snimek obrazovky- example ctd - -home-bystrousak-plocha - cherrytree 0 35 11-1](https://cloud.githubusercontent.com/assets/227282/10544504/11095412-7424-11e5-82fe-3a97686e7ee8.png)

Here is highlighted the overflown italic text:

![snimek obrazovky- example ctd - -home-bystrousak-plocha - cherrytree 0 35 11](https://cloud.githubusercontent.com/assets/227282/10544521/1d487e74-7424-11e5-9f0c-b9658108f62d.png)

**Comment by Bystroushaak** [comment] 2015-10-16 14:38
> do you have the same issue with and without spell check?

I did tested the file and I was unable to replicate the issue with spellcheck turned off. It seem like the issue may be somehow connected with spellcheck.

**Comment by Bystroushaak** [comment] 2015-10-20 22:41
I would like to urge this issue.

**Comment by giuspen** [comment] 2015-10-21 23:11
Please try the following version 0.35.11+r1662:
http://www.giuspen.com/software/cherrytree-0.35.11+r1662.tar.xz
http://www.giuspen.com/software/cherrytree_0.35.11+r1662-1_all.deb

**Comment by Bystroushaak** [comment] 2015-10-22 11:20
It seems to be working correctly now. Thanks.

**Comment by Bystroushaak** [comment] 2015-10-30 22:09
I think the problem sometimes manifests also when I open (or maybe when I close it?) the cherrytree. Can you please check that possibility? It is kinda random, so I won't be able to provide the file.

**Comment by giuspen** [comment] 2015-10-31 23:30
Hi, the problem seems to be a corruption of the formatting, but it is not
saved automatically so I don't think it could be at closing time.
I don't need a file but to understand when it could happen, one hypothesis
is at startup or selected node change time.
I'll analyse the code and try to get back with a version to test, in the
meanwhile please confirm that this happens only with the spell check
enabled.

**Comment by Bystroushaak** [comment] 2015-11-01 15:31
Yes, it never happened when the spellcheck was disabled.

**Comment by txe** [comment] 2020-10-29 20:16
was kind of resolved, closing

**Closed by txe** 2020-10-29 20:16 UTC
Labels: bug, topic: undo\redo
