### ISSUE TITLE
Debian 12 Cherrytree 1.03 - a search in several nodes logs me out from my system

### ISSUE THREAD

**Issue by He-Zu** [giuspen/cherrytree#2399] opened 2023-12-12 10:54 UTC
Debian 12
Cherrytree 1.03

sporadic error 
i do a search in several nodes. after confirming the search with Enter, the program terminates and I am logged out.
then I am at the password prompt for login
the problem did not exist in cherrytree 1.02

**Comment by giuspen** [comment] 2023-12-12 20:58
Can you try to disable, in preferences dialog, tab miscellaneous, the option to reload document after external modification and report if it does it again?
Can you also run from the terminal and report what cherrytree prints out when that happens?

**Comment by giuspen** [comment] 2023-12-12 21:50
@He-Zu are you also running xfce?

**Comment by He-Zu** [comment] 2023-12-13 07:30
Hello, my system is LMDE6 (Debian 12) with Cinnamon Desktop Kernel 6.1
I'll test the tips above this afternoon and let you know
Best regards

P.S. Many thanks for Cherrytree. It is a very helpful programm for me.

**Comment by He-Zu** [comment] 2023-12-13 13:37
hello, after i went back to version 1.02, i installed and tested version 1.03 again. i have done a search several times and the error that i am logged out has not come up again. strange. the only thing i noticed is that the window of the search result is sometimes a small window in the middle and other times it opens maximized. I am now using version 1.03 and will test if the error occurs again.
Many thanks for the support

**Comment by giuspen** [comment] 2023-12-13 19:57
Many thanks for testing@He-Zu the issue may actually be caused by the search results window. I'll get back.

**Comment by He-Zu** [comment] 2023-12-14 09:23
Hello, the error with logging out after a search has now occurred several times again.
disable the option to reload document after external modification makes no difference.
It often happens directly after the first start of cherrytree.
when i start cherrytree from the terminal i can't see any errors because i am logged out after a search and the terminal is closed.
Unfortunately, the error occurs very sporadically.
if I can test anything else just let me know
best regards

**Comment by giuspen** [comment] 2023-12-14 09:30
Thanks @He-Zu I think I fixed the issue here. I will prepare a Debian12 package for you to try later today so you can help me confirming it's all good now and I will release 1.0.4 then

**Comment by giuspen** [comment] 2023-12-14 10:38
Please try https://www.giuspen.net/software/cherrytree_1.0.3-2+10~Debian12_amd64.deb and report if the bug is fixed there

**Comment by He-Zu** [comment] 2023-12-14 11:51
i have installed the new version and will test it for a while. i will let you know if the error is gone

**Comment by He-Zu** [comment] 2023-12-14 15:29
hello, i have tested extensively.
it looks as if the error no longer occurs with the new version. 
thank you very much for the quick help.
have a nice christmas time.
best regards

**Comment by giuspen** [comment] 2023-12-14 16:04
Many thanks for your help @He-Zu have a good Christmas!

**Comment by giuspen** [comment] 2023-12-17 18:24
Fixed in v1.0.4

**Closed by giuspen** 2023-12-17 18:24 UTC
