### ISSUE TITLE
[solved] Can´t start under Windows10

### ISSUE THREAD

**Issue by BogusCurry** [giuspen/cherrytree#612] opened 2020-02-01 14:46 UTC
Hello ;D
I have the version Cherrytree 0.38.11 and the problem that I can not more start the programm. If comes a box with a message, that a I must look in a log file. And this stand it in the log file .. 

> Traceback (most recent call last):
  File "cherrytree", line 81, in <module>
  File "cherrytree", line 50, in f_main
  File "main.pyc", line 255, in main
  File "main.pyc", line 89, in __init__
  File "main.pyc", line 94, in window_open_new
  File "core.pyc", line 252, in __init__
  File "core.pyc", line 1500, in file_startup_load
  File "core.pyc", line 2002, in file_load
  File "ctdb.pyc", line 621, in read_db_full
sqlite3.OperationalError: no such table: bookmark

I hope you can this fix ;D

Greetings
Bogus

**Comment by giuspen** [comment] 2020-02-01 18:12
Is it working with an older version?

**Comment by BogusCurry** [comment] 2020-02-01 19:03
No, I have becomes the problem with the version 0.38.8. Then I have download the new version and the old I have deinstalled. The problem was not fix .. A another user mean, that the sqlite file by start was corrupted. That I would now testing ...

**Comment by giuspen** [comment] 2020-02-01 19:24
The sqlite database seems indeed corrupted, do you know where the automatic backups are and how to try and open them? They are in the same location of your .ctb file and have additional tildes at the end of the filename, you have to enable showing hidden files in order to see them and in order to try them you have to remove the trailing tildes

**Comment by BogusCurry** [comment] 2020-02-01 19:54
Ok, I have my problem fixed ;D Have change the config.cfg in config.cfg.old. Have start cherrytree and have create and save a new file ;D So I have my sqlfile load in and have save on my harddisk. The fault was maybe, that I have save the cherrytree file on a usb-stick ? 
Anyway .. I have my problem fix .. thanks for you support and for this very great program ;D

**Comment by txe** [comment] 2020-08-25 17:12
Closing because it was solved, but no data was provided to reproduce the issue.

**Closed by txe** 2020-08-25 17:12 UTC
Labels: bug, os: win, topic: read\write
