### ISSUE TITLE
Crash when importing CSV file

### ISSUE THREAD

**Issue by belzebud** [giuspen/cherrytree#1476] opened 2021-01-06 16:55 UTC
**Versions**
CherryTree 0.99.29
Windows 10

**Summary**
When importing a CSV file CherryTree crashes.
The file I'm trying to import has been attached to this report.

**Steps**
1. Open ctd file I've been adding notes to (XML format)
2. Create a new subnode
3. Click 'insert table'
4. Click 'import from CSV'
5. Select the file [Full MCS Table.zip](https://github.com/giuspen/cherrytree/files/5777025/Full.MCS.Table.zip)
6. CherryTree freezes for 10-20 seconds and crashes

**Comment by giuspen** [comment] 2021-01-07 21:48
Thanks for providing the test file I'll try and reproduce shortly

**Comment by mat8854** [comment] 2021-01-08 22:18
Hello, I can confirm import issues for **plain text files from a folder**. CherryTree freezes and crashes.

It could be a general import issue due to character encoding is my first guess.

I prepared my import files with a Python script. I will narrow it down further.

**Comment by giuspen** [comment] 2021-01-11 23:25
will be fixed in 0.99.30

**Closed by giuspen** 2021-01-11 23:25 UTC
