### ISSUE TITLE
[BUG] Scroll Zoom not always responsive mouse or Keyboard, untill clicking on another node and then returning to node zoomed

### ISSUE THREAD

**Issue by AntiNSA** [giuspen/cherrytree#237] opened 2017-03-12 11:49 UTC
Hi, sometimes when you hold ctrl+scroll wheel the window does not zoom, until changing focus onto a seperate node, however when returning to the node you were trying to zoom on you can see the zoom was indeed done.

Also, 2while more often to not is is possible to zoom out making the fonts smaller, enlarging the fonts by zooming in is not always possible.

**Comment by DiagonalArg** [comment] 2020-04-24 07:13
For me, control or alt have no effect on the behavior of the scroll wheel.  Is there some setting I need to consider to get a zoom effect?

**Comment by txe** [comment] 2020-06-19 07:11
Hi @DiagonalArg, are saying that zoom doesn't work for you? It can be caused by keyboard settings, you can read #889 to know more.
Closing this issue because I believe there is no this bug anymore.

**Closed by txe** 2020-06-19 07:11 UTC
Labels: usability
