### ISSUE TITLE
Crash on creating link with 2 words

### ISSUE THREAD

**Issue by hermann-san** [giuspen/cherrytree#591] opened 2019-11-09 19:14 UTC
When I write 2 words, highlight them and press keys crtl + L  (insert link), then Cherrytree crashes without any error message.
Insert a link on a single word works ok.
I assume that there needs to be a hyphen between the 2 words, but Cherrytree should give an error message instead of crashing, right?  

Cherrytree 38.8 on Linux Mint 19.2

**Comment by giuspen** [comment] 2019-11-13 08:03
Works for me on Mint Cinnamon 19.2, cherrytree 0.38.9. Any reason not to upgrade to 0.38.9? If still crashes on 0.38.9 give more detail

**Comment by hermann-san** [comment] 2019-11-13 13:43
I've tried it once again, and now it's not crashing anymore.
Strange, I could reproduce the crash before,  several times.

**Comment by txe** [comment] 2020-06-20 18:38
Closing, couldn't reproduce on C++ version; looking through code did not show any issue with creating links with different text selections

**Closed by txe** 2020-06-20 18:38 UTC
Labels: bug
