### ISSUE TITLE
Find in All Nodes Contents Crashes

### ISSUE THREAD

**Issue by milevyo** [giuspen/cherrytree#1460] opened 2020-12-30 02:57 UTC
**Version, Operative system**
Windows 10 64bits

**CherryTree Version**
0.99.27

**Describe the bug**
I am using CherryTree as a single file where i put all my notes and TODO lists in it. it contains about 17 root nodes that may or may not contain children {up to 3 levels max}

Trying to open search dialog on All nodes Contents {Shift Ctl F} causes CherryTree to crash

**To Reproduce**
either press the shortcut keys  {Shift Ctl F} or from search menu select 'Find in All Nodes Contents'

**Screenshots**

**Comment by giuspen** [comment] 2020-12-30 11:57
Could you share your document privately with me and tell me what to search to reproduce the issue?

**Comment by crispy-tk** [comment] 2021-01-09 20:14
Hi, I'm experiencing the same with version 0.99.29. 
I have created a new db file just to have a node to search for, and upon clicking on the Search all nodes button it crashes closing the application.

Example file attached. It's an SQLite with no encryption.
[test-search-nodes.zip](https://github.com/giuspen/cherrytree/files/5791766/test-search-nodes.zip)

**Comment by giuspen** [comment] 2021-01-10 21:25
Thanks for sharing the dB I'll try and reproduce with it shortly

**Comment by giuspen** [comment] 2021-01-13 21:21
I cannot reproduce unfortunately

**Comment by paramecie** [comment] 2021-01-15 21:07
0.99.29, Win7/64, using SHIT+CTRL+F a lot, never have had any crash, sorry can't reproduce :-(

I'd try to save AS the whole as an SQL Lite not encrypted and then play with this backup?
Like progressively removing nodes until it doesn't crash?

**Comment by crispy-tk** [comment] 2021-02-21 19:58
**Cherrytree version**: 0.99.30.0
**OS**: Windows 10/64
**System Lang**: PT-BR

Hi, I tried downloading the newer version of Cherrytree but after installation I didn't notice any changes in the behavior. It still crashed.

So, then I went to check my "Settings" configuration and found that in "Miscellaneous" there's a "Language" option. Mine wasn't set to anything at first, so I selected "English" and upon restarting the app, I proceeded to search using the "Find into all the Tree Nodes" option. And voilà! It worked!

Another test and I set it back to PT-BR. Once in "Portuguese Brazil" and upon restart, the search feature crashed again.

Hope it helps you in your investigations.

**Comment by giuspen** [comment] 2021-02-21 22:16
Thanks @crispy-tk, if you search for a word with only ASCII characters in it does it still crash? Does it crash no matter what you search for?

**Comment by crispy-tk** [comment] 2021-02-21 23:01
Yes, it does. I had entire dbs written in English only, yet it would crash just by having it set for Portuguese BR.

**Comment by milevyo** [comment] 2021-02-22 15:44
RESOLVED.

I confirm. All is OK after setting up the language  in settings.

many thanks to the one who found this solution (I am so sorry, i can not
find the email or whatever i got notified about it)




Le lun. 22 févr. 2021 à 00:01, Cristiane TK <notifications@github.com> a
écrit :

**Comment by giuspen** [comment] 2021-02-22 17:54
@milevyo what language did you set in order to stop the crash?

**Comment by milevyo** [comment] 2021-02-22 18:27
English. and I am using CherryTree version: 0.99.30


Le lun. 22 févr. 2021 à 18:55, Giuseppe Penone <notifications@github.com> a
écrit :

**Comment by giuspen** [comment] 2021-02-22 19:56
@milevyo before you selected English, (the default) was French?

**Comment by milevyo** [comment] 2021-02-22 22:51
it was unset (-)

**Comment by giuspen** [comment] 2021-02-22 23:34
@milevyo ok but was cherrytree interface in English or what language? Under means just that it tries and use the OS language

**Comment by milevyo** [comment] 2021-02-22 23:40
Yes, it was.
cherytree interface was in english and also is windows and all other
programs. but my local is set to arabic french.

**Comment by giuspen** [comment] 2021-03-09 17:45
I reproduced this thanks, will try and patch shortly

**Comment by giuspen** [comment] 2021-03-09 23:17
Will be ok in 0.99.32

**Closed by giuspen** 2021-03-09 23:17 UTC
