### ISSUE TITLE
[Feature Request] Dynamic codeboxes

### ISSUE THREAD

**Issue by telmotrooper** [giuspen/cherrytree#719] opened 2020-04-08 18:26 UTC
I've been using CherryTree for what, 5 years now? It's a tool that has made my life easier many times, but a thing that I always end up doing that wastes my time is resizing code blocks after I've filled them.

In the beginning I'm never quite sure how much height I should set in a code box, so I guess a value, type or paste whatever should be there and then resize a few times till it gets to a size which won't require scrolling but will also not end up with much blank space. I guess it's a bit of OCD of my part... Sometimes I end up changing something in a code example and have to resize the codebox again.

I wish there was an option for the codebox to resize based on the number of lines and current font and size (I wouldn't mind if it had to be locked to a specific font and size though). Maybe it could work based on explicit line breaks only or maybe it would also automatically break the line when it reaches the width set.

That's about it, thank you for this great tool. 🙂️

**Comment by metal450** [comment] 2020-06-21 19:07
Agreed. I'm a new user just getting my first data entered, & was going to report precisely this - it's a bit time-consuming entering code as each box has to be manually tweaked.  Would be awesome if it just set its height to fit its content :)

**Comment by hb20007** [comment] 2020-10-05 08:23
Duplicate of #141

**Comment by giuspen** [comment] 2020-10-05 12:05
The new auto resize of the codebox is quite good but I realized that is disabled by default, please enable it in the preferences, tab rich text, I'll change the default to enabled in the next version

**Comment by giuspen** [comment] 2020-10-05 18:37
preferences dialog, tab rich text, expand codeboxes automatically

**Closed by giuspen** 2020-10-05 18:37 UTC
Labels: enhancement
