### ISSUE TITLE
Syntax Highlighting is broken, color themes not displayed.

### ISSUE THREAD

**Issue by keyboard-penman** [giuspen/cherrytree#2493] opened 2024-04-26 20:14 UTC
Versions : 1.1.0 and 1.1.2 (using AppImage) on  Ubuntu 22.04.4 LTS

1. When inserting code nodes or code blocks within rich text nodes, the dialog to choose (syntax highlighting) language shows no language options. It's blank.
2. The default syntax highlighting language option `sh` itself produces no syntax highlighting whatsoever, even with genuine bash commands.
3. Code blocks as well as nodes do not show the color themes specified in preferences.

**Comment by giuspen** [comment] 2024-04-27 14:29
I can see that on 24.04 the AppImage doesn't even start, while runs correctly on 20.04.
I will investigate.

**Comment by keyboard-penman** [comment] 2024-04-28 06:49
> Can you try to run it from the command line and report if any error is printed?

Thanks, I shall try that.

**Comment by giuspen** [comment] 2024-04-28 13:27
I see you are using Ubuntu studio and a KDE desktop, that may be the reason I'm not seeing the issue, as I'm on a GTK desktop.
I suspect some GTK needed stuff is not in the AppImage bundle, in fact I see errors loading a couple of GTK modules.
I will try to reproduce myself on a KDE desktop.

**Comment by giuspen** [comment] 2024-04-30 20:53
Turns out the issue is visible also on a GTK desktop. I wasn't seeing it because I had the cherrytree dependencies already installed. It's visible for example also on a clean Ubuntu (Gnome, GTK) 24.04 installation. I'll see if I can find out which library files are not copied over from the AppImage  GTK script

**Comment by keyboard-penman** [comment] 2024-05-02 13:32
Thank you very much.

**Comment by keyboard-penman** [comment] 2024-05-02 14:04
> I wasn't seeing it because I had the cherrytree dependencies already installed

What are the package names of these dependencies?

Of course, a self-contained Appimage coming with these is the ideal solution, but as a temporary fix, could the problem be solved with `sudo apt install <packagename>`?

**Comment by giuspen** [comment] 2024-05-02 14:41
Correct @keyboard-penman installing the dependencies will fix the issue, if your distribution is too old though you may find an old package with incorrect dependencies.
I can paste here later the current dependencies on Ubuntu

**Comment by giuspen** [comment] 2024-05-02 14:46
I believe installing this will do for you, please confirm:

sudo apt install libgtksourceviewmm-3.0-0v5

**Comment by giuspen** [comment] 2024-05-04 14:39
I believe the issue is now fixed.
It would be very useful if you could confirm it:
1) sudo apt purge libgtksourceviewmm-3.0-0v5
2) check that you do see the issue again with the AppImage v1.1.2
3) download 
https://www.giuspen.net/software/CherryTree-1.1.2+7-x86_64.AppImage and verify that there is no issue there

**Comment by keyboard-penman** [comment] 2024-05-05 20:03
> I believe the issue is now fixed. It would be very useful if you could confirm it:
> 
> 1. sudo apt purge libgtksourceviewmm-3.0-0v5
> 2. sudo apt autoremove --purge
> 3. check that you do see the issue again with the AppImage v1.1.2
> 4. download
>    https://www.giuspen.net/software/CherryTree-1.1.2+7-x86_64.AppImage and verify that there is no issue there

Just did this.

Purging ibgtksourceviewmm-3.0-0v5 did cause the error again.

And it was fixed in the new Appimage.

Problem solved, it appears :)

Thank you so much for addressing this.

**Comment by giuspen** [comment] 2024-05-05 21:06
Excellent, many thanks @keyboard-penman for reporting and verifying the fix

**Closed by giuspen** 2024-05-05 21:06 UTC
