### ISSUE TITLE
Codebox is dangerous (CT Crashes!)

### ISSUE THREAD

**Issue by lukedreamwalker** [giuspen/cherrytree#68] opened 2015-09-29 21:57 UTC
My System:
OS: Win7x64 SP1 GER
Affected CT Version: since 0.35.9 (tested with 0.34.1, 0.35.9, 0.35.10 -> win32 portable)

Do the following to reproduce:
- Start an instance
- Add a rich text node
- Insert a codebox (Type doens't matter)
- Click inside the codebox
- Hold down return until it dies.....

The problem is the new auto grow feature of the codebox that is implemented since version 0.35.9

**Comment by giuspen** [comment] 2015-11-22 19:01
I expect this to be fixed in current 0.36.0, please test it

**Comment by bitboy85** [comment] 2016-03-25 18:54
Cannot reproduce with version 0.36.8 (windows portable) -> seems fixed :)

**Comment by Fixer-007** [comment] 2016-03-26 18:39
Please close it.

**Closed** 2016-03-26 18:53 UTC
