### ISSUE TITLE
New version 0.99.22 crashes on Formatting

### ISSUE THREAD

**Issue by mstrayer88** [giuspen/cherrytree#1372] opened 2020-11-24 23:30 UTC
**Version, Operative system**
Linux Mint 20, Xfce 64-bit. CherryTree 0.99.22.  Using SQLite Not Protected storage type.
Update was via LinuxMint Update Manager

**Describe the bug**
Multiple issues with the new version involving text formatting in the editor window:
On the menu, selected Edit > Preferences, changed the Theme of Rich Text to Classic.  Clicked Close.

Highlighted text in the editor window.  
Clicked on "Toggle Bold Property of Selected Text" on the toolbar, CherryTree crashes.
Restarted CherryTree.
Highlighted text.
On the menu, selected Formatting, clicked on "Toggle Bold Property".  CherryTree crashes.

CherryTree will also crash if I select text and try "Change the Color of the Selected Text Foreground".

Zipped a very simple .ctb file.
[Test1.zip](https://github.com/giuspen/cherrytree/files/5593337/Test1.zip)

![Screenshot_2020-11-24_18-19-41](https://user-images.githubusercontent.com/36515716/100162624-f33bcd00-2eab-11eb-8457-7c0e919e28f7.png)

**Comment by rvboyd** [comment] 2020-11-25 01:01
re: v0.99.22-2 
Wow! 
Formatting … text background/foreground color …. bold, underline, strike thru …. ALL CAUSE CHERRYTREE TO COMPLETELY CRASH. 

I will have to rollback to earlier version. Strange … sudden jump from version 0.39 to 0.99 

Uninstalled 0.99.22-2 
Installed 0.99.22-1 
Now formatting works OK.

**Comment by giuspen** [comment] 2020-11-25 07:54
0.99.22-2 is built on/for groovy (20.10), 0.99.22-1 is built on/for focal (20.04) but the source is the same, I'll need to clarify that but firstly I'll find why the 20.10 build is crashing

**Comment by ciranus** [comment] 2020-11-25 10:37
> Linux Mint 20, Xfce 64-bit. CherryTree 0.99.22. Using SQLite Not Protected storage type.
> Update was via LinuxMint Update Manager

> I will have to rollback to earlier version. **Strange … sudden jump from version 0.39 to 0.99**
> Uninstalled 0.99.22-**2**
> Installed 0.99.22-**1**

There is no cherrytree package for ubuntu  focal/groovy (only ppa).
To clarify what means "_LinuxMint Update Manager_", can you give this output:

`grep -r '^deb ' /etc/apt/sources{,.list.d/*}.list`

**Comment by giuspen** [comment] 2020-11-25 11:50
@ciranus you can download the .deb packages for 20.04 and 20.10 from the ppa web page https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages

**Comment by ciranus** [comment] 2020-11-25 12:08
@ giuspen 
Sorry. Of course I know where to DL CT packages ! 
even directly @ http://ppa.launchpad.net/giuspen/ppa/ubuntu/pool/main/c/cherrytree/

The question was addressed to mstrayer88.
I very often notice that bugs are observed on exotic distributions, and we never know where the packages are exactly coming from.

**Comment by giuspen** [comment] 2020-11-25 12:30
@ciranus a good point thanks for investigating, unfortunately this issue has been reported also on the flatpak https://www.giuspen.com/2020/11/cherrytree-0-99-22-issued/
I'm definitely sorting it out before tonight, yesterday I was setting up a 20.10 virtual machine where it is confirmed to happen but it was too slow and I was broken so went to bed. Actually @ciranus you're on 20.10 right? Can you see these crashes?

**Comment by ciranus** [comment] 2020-11-25 12:39
I currently use Debian testing and don't see this issue.
I don't see where mstrayer88 is referring to Flatpack. This is what I tried to clarify.
But question: why mstrayer88 would use Flatpack when ppa repository can be added to Linux Mint/ubuntu ???

I am convinced the exact environment should be first clarified.

**Comment by mstrayer88** [comment] 2020-11-25 15:10
grep -r '^deb ' /etc/apt/sources{,.list.d/*}.list  output:

/etc/apt/sources.list.d/additional-repositories.list:deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/18.04/mssql-server-2019 bionic main
/etc/apt/sources.list.d/mysql.list:deb http://repo.mysql.com/apt/ubuntu/ focal mysql-apt-config
/etc/apt/sources.list.d/mysql.list:deb http://repo.mysql.com/apt/ubuntu/ focal mysql-8.0
/etc/apt/sources.list.d/mysql.list:deb http://repo.mysql.com/apt/ubuntu/ focal mysql-tools
/etc/apt/sources.list.d/official-package-repositories.list:deb http://packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main
/etc/apt/sources.list.d/official-package-repositories.list:deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
/etc/apt/sources.list.d/official-package-repositories.list:deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
/etc/apt/sources.list.d/official-package-repositories.list:deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
/etc/apt/sources.list.d/official-package-repositories.list:deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
/etc/apt/sources.list.d/official-package-repositories.list:deb http://archive.canonical.com/ubuntu/ focal partner
/etc/apt/sources.list.d/pgdg.list:deb http://apt.postgresql.org/pub/repos/apt ulyana-pgdg main
/etc/apt/sources.list.d/vscode.list:deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

**Comment by mstrayer88** [comment] 2020-11-25 15:25
CheeryTree install and update as a Flatpak is what is currently offered in the Linux Mint Software Manager GUI.  Here's a pic of the flatpak history if that is any help.

![Screenshot_flatpak_history](https://user-images.githubusercontent.com/36515716/100247548-58d29c80-2f32-11eb-84f5-61da42241419.png)

**Comment by ciranus** [comment] 2020-11-25 15:25
@ mstrayer88 
Would you have something against using CT from ppa to compare ?

https://www.giuspen.com/cherrytree/#downl
https://launchpad.net/~giuspen/+archive/ubuntu/ppa

**Comment by mstrayer88** [comment] 2020-11-25 15:27
I'll give it a shot.

**Comment by mstrayer88** [comment] 2020-11-25 15:55
Looks like success!  Added your ppa.  I tried apt-get update but CT still crashed.  So I uninstalled CT, then did sudo apt install cherrytree.  Super!

**Comment by ciranus** [comment] 2020-11-25 16:14
It does not help for CT Flatpak investigation, but at least, it solves your problem !
(BTW I never use Flatpak, unless no other possibility).

**Comment by mstrayer88** [comment] 2020-11-25 16:47
Well thank you for all your help.  With the flatpak upgrade it opened my notes but lost all my preference settings.  When I installed CT from your ppa, most of my original preferences were restored.  So it's as if the flatpak upgrade created a new CT instance.  Anyway, thanks again!

**Comment by giuspen** [comment] 2020-11-25 17:55
It seems that we narrowed down to be flatpak only this crash, in fact I could not reproduce on Ubuntu 20.10

**Comment by ciranus** [comment] 2020-11-25 19:34
Who is building **1.5.6-0ubuntu0.1** CT Flatpak ?

**Comment by giuspen** [comment] 2020-11-25 20:17
I'm responsible for the flatpak, I'm building it right now from sources to see if I can fix this that could be just a building issue

**Comment by giuspen** [comment] 2020-11-26 21:17
Closing as fixed in upcoming 0.99.23

**Closed by giuspen** 2020-11-26 21:17 UTC
