### ISSUE TITLE
"Ctrl + ." doesn't increase table width, instead it will insert "e" with an underline which disappers after when you select another column!!

### ISSUE THREAD

**Issue by PranavBhattarai** [giuspen/cherrytree#1956] opened 2022-02-03 13:57 UTC
Today I was trying to a default shortkey that increases and decreases the table size.

1. `Ctrl + .` _Increases Column width_
2. `Ctrl + Alt + .` _Decrease Column width_

But these two keyboard shortkey are kind of broken, it doesn't work as intended. And for some reason, I can't find the shortkeys in **Keyboard Shortcuts**, even though we have "sections" now. 

The first shortkey does barely and the second command works sometimes if you haven't used the first shortkey. Sometimes gets triggered.
![Screencast from 02-03-2022 07 32 46 PM](https://user-images.githubusercontent.com/32763112/152357034-e54b05e6-3f64-4aa9-bb62-f1381a2cc832.gif)
```
Distro: Fedora 35 Workstation
CherryTree: 0.99.45
```

**Comment by giuspen** [comment] 2022-02-03 19:48
Thanks, duplicate of https://github.com/giuspen/cherrytree/issues/1942 I'm forced to change the keyboard shortcut because in use from the desktops - see https://askubuntu.com/questions/1372781/new-ctrl-period-key-sequence-default-in-21-10

**Closed** 2022-02-03 19:52 UTC

**Comment by PranavBhattarai** [comment] 2022-02-04 12:22
@giuspen Do we really have **Keyboard Shortkey** under **Preferences** to change this behavior? Because if we have that, the user can manually assign a shortkey, regardless of what comes by default. I thought all default/non-default shortkey can be changed manually. But is it not the case?

Sadly, and surprisingly when I just went to **GNOME Settings**> Keyboards > View & Customize Shortkeys, and used the search option to sort all shortkey which uses **Ctrl**, none of them shows the reserved shortkey for `Ctrl + .`. Which program is using it?! (Apparently emoji is using it. LOL. New thing for me.)

Let user assing shortkey for increase/decrease column width (if it's not already there).

**Comment by giuspen** [comment] 2022-02-04 14:18
Actually you are right these righ click menus of table and codebox don't have configurable shortcuts, I'll see if I can make it configurable

**Comment by PranavBhattarai** [comment] 2022-02-05 06:08
That would be great. Thanks.
