### ISSUE TITLE
Windows XP Professional SP2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#20] opened 2015-03-22 22:19 UTC
```
What steps will reproduce the problem?
1. Install
2. Start the program and the error happens
3.

What is the expected output? What do you see instead?
- I expect the program run, i see an error message.

What version of the product are you using? On what operating system?
- The problem happens on cherrytree_0.33.4_setup.exe, 
cherrytree_0.35.5_setup.exe, cherrytree_0.35.5_win32_portable.7z and 
cherrytree_0.35.6_setup.exe;

- I am using a clean Windows XP Professional SP2;

Please provide any additional information below.
- It is not a problem in Windows or PC, becausa happens same thing in a 
different machine with Windows XP SP2.
- I am attaching screenshot of error

```

Original issue reported on code.google.com by `semei...@gmail.com` on 2 Jan 2015 at 2:02

Attachments:
- [imagem.bmp](https://storage.googleapis.com/google-code-attachments/giuspen-cherrytree/issue-20/comment-0/imagem.bmp)

**Comment by txe** [comment] 2020-06-20 18:50
Closing, the issue is too old

**Closed by txe** 2020-06-20 18:50 UTC
Labels: bug, os: win
