### ISSUE TITLE
Write to C: Error

### ISSUE THREAD

**Issue by fcanapa** [giuspen/cherrytree#2507] opened 2024-05-13 20:53 UTC
**Version, Operative system**
Windows 11
CherryTree 1.1.2

**Describe the bug**
I keep getting the error "You Have No Write Access to C:" but it saves my changes anyway.

**To Reproduce**
Hit save button

**Screenshots**
The data still saves.
![image](https://github.com/giuspen/cherrytree/assets/1631740/e7331ba8-8e4f-4cc2-928e-86469e74191f)

**Comment by giuspen** [comment] 2024-05-14 18:55
Hello, what is the type of your document? (.ctd/.ctz/.ctb/.ctx/folder)?
Is that a normal folder or is that under dropbox sync with the cloud?
Does it behave the same if you try to save outside the dropbox folder?

**Comment by fcanapa** [comment] 2024-05-15 04:14
> Hello, what is the type of your document? (.ctd/.ctz/.ctb/.ctx/folder)? Is that a normal folder or is that under dropbox sync with the cloud? Does it behave the same if you try to save outside the dropbox folder?

Hello, and thank you for your reply. I forgot to mention this is using Portable (.zip) version of Cherrytree 1.1.2. I don't know if that will make a difference. The file is a ".ctb" file. I have not tried it in a non-dropbox synced directory, but I will try, then I'll update you with the results. I can say that I had been using Cherrytree in a dropbox synced directory for a long time with previous versions and never received this error. I am sure it is a Windows 11 issue. Isn't always a Windows issue? LOL  Again thank you for your response.

Frank

**Comment by orestislamprousis** [comment] 2024-11-04 20:01
Same behaviour here for me on Ubuntu after i upgraded to cherry tree 1.2.0
I did not have this behaviour before for the same file.
The file is .ctb as well.
Ubuntu version:
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"

**Comment by orestislamprousis** [comment] 2024-11-04 20:02
Also forgot to mention the file resides on my local disk

**Comment by giuspen** [comment] 2024-11-07 21:16
@orestislamprousis can you run cherrytree from a terminal (just open a terminal and type cherrytree then press enter), reproduce the issue and then copy what cherrytree printed on the terminal and paste here

**Comment by orestislamprousis** [comment] 2024-11-08 15:48
[cherry_log.txt](https://github.com/user-attachments/files/17680789/cherry_log.txt)
Hi @giuspen,
here it is. Note that i have modified my user name (you will see user instead of the real user) and i have replaced the name of my nodes with "some_name".
All the rest is intact.

I see i do not have execute permission on the mentioned file (i am the owner of the file) but even after i add the permission the issue persists. By the way i had not noticed until now but cherrytree has created a lot of cherrytree.ctb<some_number>.ctb files in my home folder. I think this has not been the case before.

**Comment by giuspen** [comment] 2024-11-13 21:40
I see @orestislamprousis you are using snap - let me ask help of a friend @hellsworth that helped me before with the snap package maybe she has a moment to help me on this? (I updated the snap recently since I needed to update the dependency gtksourcevewmm3 to gtksourceview4)
In the meantime @orestislamprousis my advice is to use the native debian package as the best experience:
1) uninstall the snap
2) install the deb from a terminal with the commands:
```
sudo add-apt-repository ppa:giuspen/ppa
sudo apt update
sudo apt install cherrytree
```

**Comment by hellsworth** [comment] 2024-11-14 05:35
hey folks! I was able to reproduce this on a 22.04 VM. For me, I was only able to reproduce this with a file in /home/heather. If the file is in /home/heather/Downloads or /home/heather/Documents - there was no problem.

I looked at the snapcraft.yaml and it seems perfectly sane to me so I opened [a discussion in the snap forum](https://forum.snapcraft.io/t/the-home-plug-grants-access-to-home-but-not-home/43982) to see if maybe we're missing some usage of the home plug.

It's also strange to me that the files being saved have that string of numbers in the filenames. I've never seen that before - @giuspen any idea what is causing that?

**Comment by giuspen** [comment] 2024-11-14 18:47
Hello @hellsworth and thanks for having a look into cherrytree's snap!
About the string of numbers that's expected, it's a temporary name used as cherrytree performs checks before approving and renaming to the correct name rotating the previous file name into the backups.
Note that I'm the snap I didn't only change the dependency but also the core version in use (sorry forgot to mention), so I will try to revert to using the previous core if there is no other solution.

**Comment by giuspen** [comment] 2024-11-14 18:51
Thanks @hellsworth we wrote almost at the same time!
I understand the problem now and will avoid doing that!
Thanks again take care.

**Comment by hellsworth** [comment] 2024-11-14 18:52
if the issue doesn't exist with core22, then we can ask in the forum discussion if there is legitimately a change on how snapd handles $HOME between core versions. I don't see why it would change.. this feels like something has changed with the way snapd handles the `home` plug.

sure anytime, just ping me :D

**Comment by giuspen** [comment] 2024-11-15 21:55
@hellsworth I would prefer to apply a solution that is at least the same per operative system as a user may switch from one package type to the other.
I think I will migrate to backup non starting with a dot if in the user home, while still detecting legacy backup paths.
I will implement this in the next few days and update here

**Comment by orestislamprousis** [comment] 2024-11-20 11:14
Hi guys,
Thanks for the updates. i appreciate it.
The issue indeed is not there if i move the file outside of the home directory.

**Comment by giuspen** [comment] 2024-11-21 20:38
This is now fixed for the next release, I have implemented the original suggestion from @hellsworth to do this only for the snap package - in case of backup in the user home directory an underscore is used instead of the dot

**Closed by giuspen** 2024-11-21 20:38 UTC
