### ISSUE TITLE
Crash when opening after updating to 0.99.34 (and.35)

### ISSUE THREAD

**Issue by CyberDroog** [giuspen/cherrytree#1619] opened 2021-04-17 07:21 UTC
Windows 7 system, using the Windows portable version of CherryTree (config.cfg file in CherryTree root folder). The app crashes almost immediately with the Windows "Stopped Working" dialog. I.e. no app window opens, it just gives the crash dialog.

If I unpack 0.99.34 (or .35) into a new folder and run it without my config.cfg file it works. Did something change with the config.cfg file after 0.99.33?

**Comment by Daxx** [comment] 2021-04-17 08:32
Possible duplicate of https://github.com/giuspen/cherrytree/issues/1610

`Enable System Tray Docking` option will have been removed by deleting config file (?)

**Comment by CyberDroog** [comment] 2021-04-17 09:04
> Possible duplicate of #1610
> 
> `Enable System Tray Docking` option will have been removed by hiding config file (?)

I manually changed both "systray=" and "start_on_systray=" to false in config.cfg and v0.99.35 starts fine now.

Thanks!

**Comment by giuspen** [comment] 2021-04-18 12:50
Thanks, fixed in 0.99.36

**Closed by giuspen** 2021-04-18 12:50 UTC
