### ISSUE TITLE
Redhat 7 - cannot install RPM, due to permission conflicts

### ISSUE THREAD

**Issue by andrasbacsai** [giuspen/cherrytree#166] opened 2016-07-21 09:44 UTC
I would like to install cherrytree on my Redhat 7 desktop workstation but I've got the following error:

>   file / from install of cherrytree-0.37.2-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
>   file /usr/bin from install of cherrytree-0.37.2-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
>   file /usr/lib from install of cherrytree-0.37.2-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64

I've done some investigation and I found the following:

```
[ab@mhzmonster Downloads]$ rpm -q --queryformat "[%{FILEMODES:perms} %{FILENAMES}\n]" filesystem-3.2-20.el7.x86_64 | grep -E " /usr/bin$| /usr/lib$| /$"
dr-xr-xr-x /
dr-xr-xr-x /usr/bin
dr-xr-xr-x /usr/lib
[ab@mhzmonster Downloads]$ rpm -qp --queryformat "[%{FILEMODES:perms} %{FILENAMES}\n]" cherrytree-0.37.2-2.noarch.rpm | grep -E " /usr/bin$| /usr/lib$| /$"
drwxr-xr-x /
drwxr-xr-x /usr/bin
drwxr-xr-x /usr/lib
[ab@mhzmonster Downloads]$ 
```

From the spec file:

```
%dir %attr(0755, root, root) "/"
%dir %attr(0755, root, root) "/usr/bin"
%dir %attr(0755, root, root) "/usr/lib"
```

Could you please review & correct it?

**Comment by gitman0** [comment] 2017-11-27 03:00
This issue most likely affects all Fedora and RHEL based systems since the filesystem rpm provides those directories.

Adding --force to the rpm command line parameters will allow installation, and only the modification time of the conflicting directories in question are changed as a result. Subsequent verification (rpm -qV) of the filesystem rpm does not report any changes to those directories.

```
[foo@lt ~]$ ls -ld / /usr/bin /usr/lib
drwxr-xr-x.  18 root root   4096 Nov 26 14:31 /
drwxr-xr-x.   2 root root  69632 Sep 29 08:09 /usr/bin
drwxr-xr-x. 241 root root 135168 Jul 18 22:43 /usr/lib
[foo@lt ~]$ sudo rpm -Uvh --force cherrytree-0.38.3-1.noarch.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:cherrytree-0.38.3-1              ################################# [ 50%]
Cleaning up / removing...
   2:cherrytree-0.38.0-2              ################################# [100%]
[foo@lt ~]$ ls -ld / /usr/bin /usr/lib
drwxr-xr-x.  18 root root   4096 Oct 29 21:03 /
drwxr-xr-x.   2 root root  69632 Nov 26 21:48 /usr/bin
drwxr-xr-x. 241 root root 135168 Oct 29 21:02 /usr/lib
[foo@lt ~]$ rpm -qV filesystem
[foo@lt ~]$ 
```

**Comment by poleguy** [comment] 2019-02-20 00:01
This also happens on centos 7.

`sudo rpm -Uvh playbook/roles/cherrytree/files/cherrytree-0.38.7-1.noarch.rpm 
Preparing...                          ################################# [100%]
	file / from install of cherrytree-0.38.7-1.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64
	file /usr/bin from install of cherrytree-0.38.7-1.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64
	file /usr/lib from install of cherrytree-0.38.7-1.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64
`

Your work-around is fine except that I'd like to deploy from ansible which doesn't seem to have a 'force' command in the yum module. It would be nice to fix this.

**Comment by txe** [comment] 2020-10-29 21:33
Closing, the issue with filesystem was caused by wrong package structure, it was fixed.

**Closed by txe** 2020-10-29 21:33 UTC
Labels: bug, topic: install\running\future
