### ISSUE TITLE
New folders are out of order

### ISSUE THREAD

**Issue by G3rmman** [giuspen/cherrytree#1263] opened 2020-10-19 18:46 UTC
**Version, Operative system**
State the Version and the Operative System/Desktop. Try the latest available version before reporting an issue.

**Describe the bug**

**To Reproduce**
If applicable, attach a non-personal document where the issue can be reproduced systematically.

**Screenshots**

**Comment by G3rmman** [comment] 2020-10-19 18:55
I recently started a new notebook after upgrading to 0.99.  The new folders that I create get reshuffled when I open CherryTree again later.  They seem to always get moved to the top of the list.
![CherryTree Bug Report](https://user-images.githubusercontent.com/72406773/96499182-b2002f80-1212-11eb-8828-d65187425920.png)

**Comment by ciranus** [comment] 2020-10-23 08:38
> **Version, Operative system**
> State the Version and the Operative System/Desktop.

Windows version X ?
I cannot reproduce in linux.

**Comment by G3rmman** [comment] 2020-10-23 15:34
Windows 10 Pro

**Comment by ciranus** [comment] 2020-10-23 16:39
Which sorting method did you choose ?

![2020-10-23_5](https://user-images.githubusercontent.com/61602511/97030450-139c0300-155f-11eb-98a9-c5b367325bdf.png)

**Comment by G3rmman** [comment] 2020-10-23 17:05
I used "Sort Tree Ascending", which did temporarily did reorganize the folder correctly.
For a test, I created a new sub-folder, labeling it "Chapter 5: TEST FOLDER". Notice in the screenshots what happened from the time I created the folder to the time I reopened CherryTree:
![Test Folder 1](https://user-images.githubusercontent.com/72406773/97032728-e2eca700-1527-11eb-88d6-7a583b94ef1e.png)
![Test Folder 2](https://user-images.githubusercontent.com/72406773/97032744-e8e28800-1527-11eb-8b4d-787be54a3c0e.png)
![Test Folder 3](https://user-images.githubusercontent.com/72406773/97032755-ec760f00-1527-11eb-8967-58a3091ba47e.png)

**Comment by ciranus** [comment] 2020-10-23 18:35
Could you export this test node as 'Cherrytree Document' > XML not protected, and share it ?

**Comment by G3rmman** [comment] 2020-10-23 18:50
It appears that GitHub does not allow sharing anything past picture files, plain text files, Microsoft Office documents, PDF's, and ZIP files.  Should I email the .ctd file to you?
![Share File Types Accepted](https://user-images.githubusercontent.com/72406773/97042475-b5f3c080-1536-11eb-974f-29d1977377ba.png)

**Comment by G3rmman** [comment] 2020-10-23 18:52
[A+ Certification Notes.zip](https://github.com/giuspen/cherrytree/files/5431317/A%2B.Certification.Notes.zip)

**Comment by G3rmman** [comment] 2020-10-23 18:53
[Test Node.zip](https://github.com/giuspen/cherrytree/files/5431328/Test.Node.zip)

**Comment by ciranus** [comment] 2020-10-23 19:06
Ok great. Tested in linux, but I cannot reproduce your problem.
To be confirmed by a windows user.

**Comment by userfav** [comment] 2020-10-24 14:50
Can confirm on Windows 10, version 0.99.16, portable mode (all settings default).
Steps taken: Open CherryTree > created node called "parent node" > created tree subnodes called "sn 1", "sn 2" and "sn 3". Saved the file as Sqlite (not protected). Exit Cherry tree. Open again, create a subnode "sn 4" (below "sn 3") . Save the ctb file. Exit. Open Cherrytree again and "sn 4" stands first in the subnodes list of "parent node".

If you created another one ("sn 5") the subnode stand below the subnode "sn 4" after restart.

![image](https://user-images.githubusercontent.com/46328784/97084657-00387880-15ef-11eb-84ae-a1d5a1547fbf.png)

**Comment by txe** [comment] 2020-10-27 21:05
Thanks for report, the fix will be in the next release 0.99.18

**Closed** 2020-10-27 21:04 UTC
