### ISSUE TITLE
feature request: Scroll past the end

### ISSUE THREAD

**Issue by krisko** [giuspen/cherrytree#136] opened 2016-05-24 13:28 UTC
Hi,
I've got interesting feature to implement in cherrytree...
Could you add option to allow scrolling past the end of text in node.
Example: I always add number of empty lines at the bottom of file, to be able to scroll text to the middle of screen, or just higher from the bottom.

Thank you

**Comment by giuspen** [comment] 2016-05-24 17:56
Hi, I also would find this useful personally since I use this in geany. In
future I will try to achieve it.

**Comment by hb20007** [comment] 2019-08-20 11:03
Duplicate of #109

**Comment by txe** [comment] 2020-09-15 20:37
Resolved by #1162 for C++ version, Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line

**Closed by txe** 2020-09-15 20:37 UTC
Labels: enhancement, topic: ui
