### ISSUE TITLE
Export and print issues on Windows

### ISSUE THREAD

**Issue by lmattcris** [giuspen/cherrytree#2045] opened 2022-05-17 15:41 UTC
**Version, Operative system**
Windows 11 Pro, 21H2
Build 22000.675

**Describe the bug**
Using CherryTree 0.99.47 and trying to export a PDF I obtain an unreadable file (tried readers as Sumatra PDF, Firefox, Edge); apparently, the file created isn't closed, and complete, as it can't even be deleted until I completely close CT.
Trying to print to PDF (used the stock "Microsoft PDF printer") the application hangs for a short while, then crashes without any message.
I tried reinstalling, and restarting the system, to no avail.
Stepping back to version 0.99.46 everything works again (exporting, printing).

**To Reproduce**
This happens systematically with any **ctb** file I tried
1. Open the ctb file
2. Select Export to PDF
3. Give a valid path/name
4. The file is created, though incomplete and locked

**Screenshots**

**Comment by giuspen** [comment] 2022-05-17 21:15
Can you try the portable only test version I created for you 0.99.47.1:
https://www.giuspen.com/software/cherrytree_0.99.47.1_win64_portable.7z
After extraction double click on \cherrytree_0.99.47.1_win64_portable\mingw64\bin\cherrytree.exe
If it still fails, can you enable the log in the preferences dialog, tab miscellaneous, then reproduce the issue and paste the debug log content here? (or attach it here)

**Comment by giuspen** [comment] 2022-05-19 21:06
Ok this makes more sense now. It is likely that what is causing the issue is a particular node. I would need you to share with me something to reproduce the issue if you want me to fix it

**Comment by lmattcris** [comment] 2022-05-20 06:51
Good, I've nailed down the single node that generates the error, I exported it to a CTB, and it still shows that behavior when re-exporting to PDF. This is not a particularly reserved document, but how can I send it to you privately?

**Comment by giuspen** [comment] 2022-05-20 19:07
you can find my email address in cherrytree help--about dialog

**Comment by Zeno001** [comment] 2022-07-22 22:44
Only just started using CherryTree but I think I'm getting the same issue in 0.99.48. I traced it to a long Google cache URL that I'd added as text in one node and a snippet of a script I'd pasted in as text from the source code of a Facebook page in another node. When I tried to export as a pdf (either just that node or the whole tree), CherryTree crashed leaving a zero-sized pdf.

Putting both the URL and the code snippet into code blocks allowed the creation of the pdf for those specific nodes and for the whole tree.

Even having done that, the export HTML of the whole tree crashes CherryTree but I've not had time to track down the source of that.

**Comment by giuspen** [comment] 2022-07-23 14:58
@Zeno001 it would be very useful to me if you could send me a test document that crashes cherrytree when exporting

**Comment by Zeno001** [comment] 2022-07-23 15:20
Hi

GitHub won't let me attach a ctb file but a simple tree with just one node and any Google cache URL pasted in as text seems to do it. Just create a new instance and add the Google cache URL for your CherryTree home page as text:

http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fwww.giuspen.net%2Fcherrytree%2F&rlz=1C1CHBF_en-GBGB894GB894&oq=cache%3Ahttps%3A%2F%2Fwww.giuspen.net%2Fcherrytree%2F&aqs=chrome..69i57j69i58.1833j0j4&sourceid=chrome&ie=UTF-8

Export as pdf and CherryTree crashes.

However, removing the extra parameters in that URL to give:

https://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fwww.giuspen.net%2Fcherrytree%2F

...works fine and the pdf is created, so it must be something in those additional parameters that causes the problem.

I've not looked at the script code snippet that also caused a crash but I suspect it will be much the same?

**Comment by giuspen** [comment] 2022-07-24 20:13
Nice report @Zeno001 thanks, will be fixed in next version

**Closed by giuspen** 2022-07-24 20:13 UTC

**Comment by Zeno001** [comment] 2022-07-24 20:23
Great! Glad to help.
