### ISSUE TITLE
0.99.15

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1232] opened 2020-10-08 22:04 UTC
Just done a few tests with the latest version. After this and that now it behaves as if the option "Rich Text/show spaces" is _always on_. That is, instead of spaces, little light gray dots are shown. Switching the option yields no effect. Screenshot attached.
[2020-10-09 00_03_02-Clipboard.jpg.zip](https://github.com/giuspen/cherrytree/files/5351476/2020-10-09.00_03_02-Clipboard.jpg.zip)

**Comment by crogonint** [comment] 2020-10-09 06:23
Win7 x64, mine works as expected.

**Comment by Hoffenbar** [comment] 2020-10-09 18:21
Very strange - now the phenomene is gone... don't know whats the difference besides newly starting the program.... i will observe further...

**Comment by txe** [comment] 2020-10-26 13:47
Cannot reproduce, so closing

**Closed by txe** 2020-10-26 13:47 UTC

**Comment by crogonint** [comment] 2020-10-26 20:14
I just wanted to point out that back in the day, NO programs worked right
(after install) until you rebooted the freaking computer. This is most
likely an issue with WIndows failing to hook something to the program that
it should just automatically do anyway.. until you restart the program.

Probably.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
