### ISSUE TITLE
[bug] Non-English characters garbled when pasted from 3rd party program

### ISSUE THREAD

**Issue by dardoor** [giuspen/cherrytree#1336] opened 2020-11-14 17:59 UTC
When I paste non-English characters from a third party app they get converted to something weird in CT.

Steps to reproduce, for example:
1. Open Notepad.
2. Write or paste the letter ü into Notepad.
3. Select it in Notepad and copy it.
4. Paste it in CherryTree.

The result is not ü, but Ã¼.
Copy-pasting ü from Firefox instead of Notepad produces ΓΌ.

Other non-English characters produce different results when pasted and they also change if they're in combination with other characters—if it's an entire word, for example ... sometimes they're even pasted correctly, if it's the "right" combination.

CherryTree 0.99.20 portable, Windows 7 64bit.

**Comment by dardoor** [comment] 2020-11-15 10:31
This doesn't happen with 0.99.17, so it must have been some recent change that caused it.

Also reproduced on Windows 10.

**Comment by giuspen** [comment] 2020-11-15 11:30
Thanks I'll take a look

**Comment by giuspen** [comment] 2020-11-15 12:01
I tried on windows 10 with Firefox, Edge and notepad and couldn't reproduce. Can you give me a specific test case?

**Comment by dardoor** [comment] 2020-11-15 14:08
I can reproduce this every time. I now tried in a VM with W10 (20H2), with almost nothing else installed. Just extracted CT, ran cherrytree.exe and created a new node, nothing else. Here's a screenshot, copying the character è from Character Map to CT:

[https://i.imgur.com/VPiiXQj.png](https://i.imgur.com/VPiiXQj.png)

**Comment by dardoor** [comment] 2020-11-16 09:55
Also it doesn't happen in version 0.99.19. It's a problem with 0.99.20 only.

**Comment by giuspen** [comment] 2020-11-18 22:45
fixed in 0.99.21

**Closed by giuspen** 2020-11-18 22:45 UTC
