### ISSUE TITLE
Triple click does not select the whole paragraph

### ISSUE THREAD

**Issue by phoe** [giuspen/cherrytree#592] opened 2019-11-13 21:32 UTC
Triple clicking on `They` at the beginning of this sentence should highlight the whole paragraph, but instead it highlights only text up to the first line-wrapping linebreak.

![Zrzut ekranu z 2019-11-13 22-32-06](https://user-images.githubusercontent.com/15045546/68806112-7b668000-0665-11ea-9707-0d3a6fc18e09.png)

**Comment by letto4135** [comment] 2020-02-14 15:55
I'm just gonna ask... Why should triple clicking highlight the paragraph? Double is word, triple is line.. Maybe a quad click method could add this functionality?

**Comment by phoe** [comment] 2020-02-14 15:58
In the editors that I have worked with so far, triple click selects the whole paragraph. Selecting a line is counter-intuitive to me, since what is called "line" depends at every given moment on the width of the editor and font size.

I am fine with using a quad-click for that instead, since it solves my actual problem of being unable to highlight a paragraph using only mouse clicks.

**Comment by letto4135** [comment] 2020-02-14 16:13
Yeah I see what you mean. I had to open word and try it there because I've never triple clicked something.. -_-

**Comment by letto4135** [comment] 2020-02-14 17:16
It looks like the issue is double click was the only 'defined' action, so triple click is a default action. Triple click needs overwritten to match a paragraph instead of a line.

**Comment by txe** [comment] 2020-08-25 16:56
This issue is fixed, so closing

**Closed by txe** 2020-08-25 16:56 UTC
Labels: bug

**Comment by phoe** [comment] 2020-08-25 17:13
Amazing! Thank you!
