### ISSUE TITLE
loss of data when saving to a full disk

### ISSUE THREAD

**Issue by rvertesi** [giuspen/cherrytree#2098] opened 2022-08-16 07:53 UTC
**Version, Operative system**
cherrytree snap on ubuntu 20.04 as of 2022-08-05

**Describe the bug**
When the disk is full, trying to save an open ctd results in an error but the existing file output gets overwritten with a zero-size file. Attempting to save multiple times results in all the tilde backup files being written over with zero-size files and thus the note is completely lost.
Note: this happened to one of my colleagues so I cannot verify it directly but this is what we figured from the file access dates. Still I believe it would be worth a quick look.

**To Reproduce**
filling up the disk, trying to save an existing note multiple times

**Comment by giuspen** [comment] 2022-08-17 20:06
The snap package is unfortunately still pointing to the obsolete python package.
I will look at it myself and try to upgrade because too many people are using it thinking that it is an up to date version.
@hellsworth could you please pass to me the rights to handle the snap cherrytree package https://snapcraft.io/cherrytree

**Comment by giuspen** [comment] 2022-08-17 20:37
The snap package states that it is version 0.99.36 but that is wrong. It is in fact version 0.39.4 - the latest python version.
`giuspen@u1804:~$ ps aux | grep cherrytree
giuspen  11073  0.7  1.5 297240 61296 pts/0    S+   21:27   0:01 python2.7 /snap/cherrytree/40/usr/bin/cherrytree`

**Comment by hellsworth** [comment] 2022-08-17 20:39
So sorry, I just got swamped with other things. @giuspen I've added you as a collaborator on the snap so you should be able to push to the snap store. I can also try again to update it. Last time I checked, there was a hangup with needing the newest gtksourceviewmm version that wasn't quite available in core22 yet. Since core22 was released recently (a month or so ago), that problem should be solved. I can give the build another try this week too.

**Comment by giuspen** [comment] 2022-08-17 20:41
Thanks @hellsworth for your work, I'll try and upgrade it in the next days to deliver the latest C++ version

**Comment by hellsworth** [comment] 2022-08-22 19:32
@giuspen Interesting. I am running the snapcraft in latest/stable and it definitely builds. My host is Ubuntu 22.01.4. I believe you're on Fedora.. and just last week I had issues setting up a Fedora VM so I can try to chase that down (I need it anyways for general snap testing) and try building there. In the meantime, if you want to email me the full build log, I can pass it along to the snapcraft guys to get their thoughts :)

**Comment by giuspen** [comment] 2022-08-22 19:38
@hellsworth I'm on Linux Mint based on 22.04. The snap does build, the problem is after installed and run cherrytree in a terminal, then when I try and insert a LatexBox it fails and prints that error.
In that contest cherrytree is calling a system() to the binary latex which is installed in the snap bundle.

**Comment by hellsworth** [comment] 2022-08-22 21:54
I see the same thing now an I've been trying a few things to no avail (setting PATH and TEXMFLOCAL to the correct path where texmf.cnf lives). A coworker suggested a layout instead so I can try that tomorrow and get back to you!

**Comment by giuspen** [comment] 2022-08-23 17:15
Thanks @hellsworth if it's not simple don't worry I can use a Linux 64 bit portable archive for latex/dvipng that I already use for the flatpak and appimage that I can try and bundle into the snap

**Comment by hellsworth** [comment] 2022-08-23 21:51
Well if you add this, it fixes the texmf.cnf error:
```
$ git diff snap/snapcraft.yaml
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 7e5477e8..0f0c7dc9 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -31,6 +31,12 @@ plugs:
 
 assumes: [ command-chain ]
 
+layout:
+  /usr/share/texmf:
+    bind: $SNAP/usr/share/texmf
+  /usr/share/texlive:
+    bind: $SNAP/usr/share/texlive
+
 parts:
   cherrytree:
     plugin: cmake
```
But then you hit a perl error:
```
Can't locate Pod/Usage.pm in @INC (you may need to install the Pod::Usage module) (@INC contains: /usr/share/texlive/tlpkg /usr/share/texlive/texmf-dist/scripts/texlive /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/texlive/texmf-dist/scripts/texlive/mktexlsr.pl line 100.
BEGIN failed--compilation aborted at /usr/share/texlive/texmf-dist/scripts/texlive/mktexlsr.pl line 100.
Compilation failed in require at /snap/cherrytree/x1/usr/bin/mktexfmt line 26.
BEGIN failed--compilation aborted at /snap/cherrytree/x1/usr/bin/mktexfmt line 28.
[2022-08-23 15:42:26.946] [   ] [error] system(latex --interaction=batchmode -output-directory=/tmp/.MP1QR1 /tmp/.MP1QR1/1-5267-__ct_special.tex > /dev/null) returned 256
```
I've heard that texlive can be rough to work with, and quite large. Have you considered using textiny? I can give that a try in the snap to see if it's any easier..

**Comment by hellsworth** [comment] 2022-08-24 03:20
Well I tried tinytex and run into a permissions issue running latex (when the latex box is inserted). For reference, [here's my yaml](https://paste.ubuntu.com/p/SvQBGF8bjS/) and my error:
```
sh: 1: latex: Permission denied
```
so maybe text-live-base is the way to go..

**Comment by giuspen** [comment] 2022-08-24 17:30
Thanks for your help @hellsworth I'll make few attempts myself now

**Comment by hellsworth** [comment] 2022-08-24 17:32
You bet! One thing one of the snapcraft devs suggested that I haven't looked at yet is "perl might already be in the snap and might be solved by changing the perl include path or by using another layout". So you can give that a try :)

Also maybe open another issue for getting the snap build working with latex? I see we've overloaded this other issue..

**Comment by giuspen** [comment] 2022-08-24 19:57
@hellsworth I succeeded. I'll try and upgrade the snap later today or tomorrow. I'll close this ticket as referring to an obsolete version.

**Closed by giuspen** 2022-08-24 19:57 UTC
