### ISSUE TITLE
There is a problem with the width of Chinese characters, which is bolded by default.

### ISSUE THREAD

**Issue by button541** [giuspen/cherrytree#1661] opened 2021-04-30 08:55 UTC
Environmental description:
Operating system: windows 10 64 bit
cherrytree version：0.99.36

When editing a document, I found that the program does not support Chinese fonts very well, and the font width is abnormal, as if it is bold, as shown in the figure below:
https://github.com/button541/images/blob/main/QQ%E6%88%AA%E5%9B%BE20210430161658.png

I looked up the settings of cherrytree and wanted to modify the font width. After I discovered the CTRL + M shortcut key and executed this command, it achieved the effect I wanted: Chinese fonts and English fonts have the same width. See below.
https://github.com/button541/images/blob/main/QQ%E6%88%AA%E5%9B%BE20210430163734.png

but after inputting Chinese, I need to execute commands to modify the font width, which reduces my writing efficiency. Hope to cancel the default setting of increasing the Chinese font width, or increase the default setting of reducing the Chinese font width.

**Comment by ciranus** [comment] 2021-04-30 09:42
> When editing a document, I found that the program does not support Chinese fonts very well, and the font width is abnormal, as if it is bold

Do you confirm this is specific to CT, and you don't see this in a different text editor ?
It can be a font issue which does not contain bold for a given font size (due to specific drawing accuracy required by chinese characters).

**Comment by button541** [comment] 2021-05-01 02:50
@ciranus yes, I'm sure.

**Comment by ciranus** [comment] 2021-05-01 09:54
Can you make a text node with your example, export it as CT > xml document, and sent it back here.

**Comment by button541** [comment] 2021-05-01 16:14
@ciranus 
No problem, but why is this necessary? The probability of recurrence of this problem should be 100%.
The following is the url of the ctd file and the url of the related image.
https://github.com/button541/miscellaneous/blob/main/Test_Chinese_text_broadband.ctd
https://github.com/button541/images/blob/main/QQ%E6%88%AA%E5%9B%BE20210502000829.png

**Comment by ciranus** [comment] 2021-05-01 16:30
This does not illustrate the problem you tried to describe in your first message.

**Comment by giuspen** [comment] 2021-05-01 17:33
I'm not sure what I can do to help you with this, it looks like a font issue, have you tried to select other fonts in the preferences dialog?

**Comment by button541** [comment] 2021-05-02 13:05
@giuspen Thanks for your suggestion, I am using Courier New now.
I tried to modify the font settings. Some fonts display very well, such as fangsong, microsoft JhengHei, and simsun. The text displayed using these fonts is not bold, and the font bandwidth of Chinese and English characters is not different.

**Comment by button541** [comment] 2021-05-02 13:09
@giuspen Thanks for your suggestion, I am using Courier New now.
I tried to modify the font settings. Some fonts display well, such as fangsong, Microsoft JhengHei and simsun. The text displayed using these fonts is not bold, and the font width of Chinese and English characters is the same.

**Comment by button541** [comment] 2021-05-02 13:26
@giuspen @ciranus 
This should be a font compatibility issue. I have not encountered this phenomenon when using other notebook software, so I still think it is a cherry tree problem.
This is a small problem, if there is a more serious problem, please go and deal with it. This did not have a big impact on me.

**Comment by ciranus** [comment] 2021-05-02 13:34
@button541 
Your mixed regular/bold styles you mentionned in your first message, not reproduced in your 3rd message, were very likely not caused by any font, but more by some hidden styles (after some copy/paste operations for example).
This is why I wanted to see the exported xml file to verify.

Now you say:
> Some fonts display well, such as **fangsong**, Microsoft **JhengHei** and **simsun**. The text displayed using these fonts is not bold.

Can you precisely summarize what is your current problem with **chinese** characters, and show which difference you see with an another editor, and explain what is your expected result ?

Chinese fonts in my linux system are bitmap fonts requiring fonts-unifont & xfonts-unifont, then a bit special anyway.
I cannot reproduce any difference with chinese characters between CT and Kate editor in my system.

**Comment by button541** [comment] 2021-05-03 07:42
@ciranus 
My job is an operation and maintenance engineer. I mainly use cherry tree to record some code snippets and problem handling process, and also use cherry tree to make study notes.
The problem encountered now: the font width of the Chinese characters and the English characters entered in the cherry tree text are different, and the width of the Chinese characters is wider than the English characters, as if the bold operation was used.
I have changed a lot of fonts in the cherry tree and have this phenomenon. When other text editors use the same font, there is no difference in the width of Chinese and English characters.
Expected result: Chinese characters and English characters are of equal width.

**Comment by ciranus** [comment] 2021-05-03 08:40
Understood, but some snapshots to show differences may help a lot.
Let's consider this text block:
```
这是一段测试用的文字，对这一段的所有字符使用了快捷键修改了字体的等宽属性
0123456789001234567890012345678900123456789001234567890012
```
This is what I have in CT with monospace font:
![ksnip_20210503-101908](https://user-images.githubusercontent.com/61602511/116855081-0b510e80-abf9-11eb-85b7-849960c27fed.png)

Now to compare with **Kwrite** text editor, I can get different results, depending on the font choice:

DejaVu Sans Mono font:
![ksnip_20210503-103229](https://user-images.githubusercontent.com/61602511/116856144-e8bff500-abfa-11eb-8709-5845ee7905fb.png)

FreeMono font
![ksnip_20210503-102935](https://user-images.githubusercontent.com/61602511/116855907-7d762300-abfa-11eb-8adf-e631b8acf62f.png)

Liberation Mono
![ksnip_20210503-103119](https://user-images.githubusercontent.com/61602511/116856074-c29a5500-abfa-11eb-9e58-eb27040a875f.png)

I then don't see anything special to CT, in my environment.
Which is the right one ? 
I would intuitively say that chinese characters need more spacing due to required drawing accuracy, for same readability compared to other characters.

**Comment by giuspen** [comment] 2021-05-03 08:50
I think @button541 should just select a font that is monospace to ensure that all characters have the same width if this is what he wants.

**Comment by ciranus** [comment] 2021-05-03 08:54
The problem is... you don't get the same spacing even with monospace fonts, when you mix chienese/latin characters. This is not specific to CT, as long as  button541  does show any difference.

**Comment by giuspen** [comment] 2021-05-03 08:58
I see... as @ciranus says there is nothing that CT can do about this

**Comment by ciranus** [comment] 2021-05-03 08:59
You even illustrate the problem in the code tag of this forum
```
这是用
01234
```

**Comment by button541** [comment] 2021-05-03 13:53
@giuspen @ciranus 
Thank you both.
As I said in the above reply, this is a small problem, which can not be solved and has no great impact.

**Comment by ciranus** [comment] 2021-05-03 19:19
@button541
Before closing this non-CT issue, I still miss why:
1 - you don't clearly say with which editor you are able to mix TrueType + Bitmap characters with same spacings
2 - show a snaphot to demonstrate
3 - clearly say which monospace font to use to achieve this result.
Maybe we would at least learn something.

To demonstrate, just copy/paste the text block below and show that you can get 20 chinese characters with same spacing as for 20 latin characters.

```
01234567890012345678900
这是一段测试用的文字，对这一
```

**Comment by button541** [comment] 2021-05-04 06:30
@ciranus 
![wiznote](https://user-images.githubusercontent.com/80081518/116967494-f94c9a00-ace4-11eb-8103-428ec5882e72.png)
![cherrytree](https://user-images.githubusercontent.com/80081518/116967540-17b29580-ace5-11eb-9748-4b1f6b7aa844.png)
![notepad](https://user-images.githubusercontent.com/80081518/116967558-213bfd80-ace5-11eb-97da-5f611d00d32c.png)

**Comment by ciranus** [comment] 2021-05-04 08:24
You then have exactly the same spacing problem when mixing chinese/latin characters for all other applications right ?
You clearly see that for the same font, the length of 20 chinese characters is totally not same as latin characters length.
This is not what you claimed before, or I am totally confused within your messages.
I wonder if you should not simply close this non CT issue.

**Comment by button541** [comment] 2021-05-04 14:13
No, the cherry tree performance is more obvious.

**Closed** 2021-05-07 15:18 UTC
