### ISSUE TITLE
Very slow find by node name since updating to 1.0.4

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#2408] opened 2023-12-18 16:38 UTC
On both Windows & Linux, since updating from 1.0.2 to 1.0.4, searching by node name has become very noticeably slower. Previously it would find the node more or less instantly (you type Ctrl+T, type the name, hit enter, and the result window pops up more or less instantly). Now after hitting enter it goes through a lengthy progressbar, more similar to as if I were searching through full node content.  After the first time I search by node name it does seem to be a bit faster during follow-up searches, but previously, I never had to wait for search by node name at all.

Using a "multiple files" db.  Tree size is 1559 nodes.

**Comment by giuspen** [comment] 2023-12-18 21:36
Thanks for reporting @metal450 I understand, this has been caused by the additional checks that I introduced to support losing access to the open document without crashing.
I can certainly optimise when only searching for node name and tags so restore the previous speed. I'll get back.

**Comment by giuspen** [comment] 2023-12-22 21:00
I should have fixed this and the speed of searching in nodes names only should be again as before v1.0.2.
I can create 1-2 packages for you if you wish to try yourself

**Comment by metal450** [comment] 2023-12-22 22:27
If you'd like me to test, sure, happy to. If you're just doing it for my benefit, no worries - I rolled back to 1.0.2, so I can just wait until the next release, assuming it isn't super far off :)

**Comment by giuspen** [comment] 2023-12-23 11:49
Cheers @metal450 - the next release 1.1.0 will be in 1 to 2 months unless critical issues are found - in that case I will issue 1.0.5

**Comment by metal450** [comment] 2023-12-24 03:58
Sounds good!

**Comment by metal450** [comment] 2024-03-22 02:17
Just updated to 1.1.0; Ctrl+T now never returns any results (it always says 0 matches).

**Comment by giuspen** [comment] 2024-03-22 07:27
Sorry about that I will release a fix in a few days

**Comment by giuspen** [comment] 2024-03-23 22:28
This should be now fixed. If you could try the test build from https://www.giuspen.net/cherrytree/#testing (called 1.1.0+5) and report if that works as expected or still has issues it would be very useful

**Comment by metal450** [comment] 2024-03-24 01:19
Yup, search works as expected :)

Just one small observation: there seems to be a new graphical glitch thing - upon the search finishing, there's a strange bar across the bottom of the notes area. It disappears as soon as you focus in the text area, change to another search result, or do anything really.  Like this:
![2024-03-23 18 17 52](https://github.com/giuspen/cherrytree/assets/1877409/8cbea99c-5017-4d9c-a151-2475fff301b1)

Functionally though, it's back in order :)

**Closed** 2024-05-05 16:05 UTC
