### ISSUE TITLE
[0.99.5 in Kubuntu 20.04] F2 function 'Use selected color' cannot be deselected / stays selected

### ISSUE THREAD

**Issue by gerdeg** [giuspen/cherrytree#1023] opened 2020-07-19 08:17 UTC
1/ F2 function 'Use selected color' cannot be deselected / stays selected.
2/ Undo does not work on changes in the tree

Ger de Gooijer

**Comment by giuspen** [comment] 2020-07-19 12:12
The undo machine is not supporting undoing changes to the tree at the moment, same as it was for the Pygtk2 version. F2 is to open the node properties dialog, isn't it?

**Comment by gerdeg** [comment] 2020-07-19 12:52
Yes, it is. Or you right-click for Change Node Porperties of course.

**Comment by txe** [comment] 2020-07-29 22:19
Closing because these are not issues?

**Comment by gerdeg** [comment] 2020-07-30 06:36
Point " 1/ 'Use selected color' cannot be deselected / stays selected." is an issue :-)

**Comment by txe** [comment] 2020-07-31 17:06
> Point " 1/ 'Use selected color' cannot be deselected / stays selected." is an issue 

Can you paraphrase this? I don't understand what I should do to reproduce it.

**Comment by gerdeg** [comment] 2020-08-01 09:41
In steps:
-Select aan item in the tree you want to give another text color;
-Press the default F2 or rightclick and choose  'Change Node Properties'
-Select  'Use Selected Color' for instance the color red and click ok
-The text color of the item in the tree is now red.
-You decide you want to go back to the default text color for that item.
-So you press the default F2 again or rightclick and choose  'Change Node Properties'
-Now you DESELECT 'Use Selected Color' to get the default color back again and click ok
-The text color of the item in the tree is still red and not the default color as should be the case.
I did this just a minute ago in 0.99.6.

**Closed** 2020-08-01 19:08 UTC
