### ISSUE TITLE
Minimize to tray bar and restore issue on Win10 and dual screen

### ISSUE THREAD

**Issue by lmattcris** [giuspen/cherrytree#1943] opened 2022-01-27 11:29 UTC
**Version, Operative system**
CherryTree 99.45, running on Windows 10 Pro 21H2

**Describe the bug**
I'm using a dual monitor setup, a laptop with its screen (screen 1), and an external monitor (screen 2) that I use as the main display. If I minimize the application the system tray bar with _Hide_ (Ctrl+Q) and click again the icon to restore, it always shows back on screen 1, even though used and stored on tray bar on screen 2

**To Reproduce**
1. I open the application, and on the first start, it *always* shows on screen 1
2. I move the window to screen 2, and work there; minimizing the window to the **taskbar**, and restoring it, pops up again on screen 2; fine
3. If I select File | Hide or press Ctrl+Q, it's stored in the **tray bar**, as expected
4. When I double click the cherries icon in the tray bar the application is restored to screen 1 (while I'd expect it to restore to screen 2). The same behavior happens with a shortcut key assigned to the application icon on Windows' desktop: pressing the assigned key restores it always to screen 1.

**Comment by giuspen** [comment] 2022-02-05 18:40
I can see it it's very annoying, looks like a Gtk3 issue on windows, I'm trying to find a workaround but without success so far, may have to wait for library fix

**Comment by giuspen** [comment] 2022-02-11 12:39
Raised https://gitlab.gnome.org/GNOME/gtk/-/issues/4690

**Comment by paramecie** [comment] 2022-02-13 22:08
Ciao!

Same here, for a week maybe CT systematically opens on the wrong monitor 2.

I tried anything, including moving resizing, minimizing, etc. - opening another file, whatever.
It still opens everything in screen 2 (left) while my taskbar and main screen is 1 (right).

No problem with other apps.

I checked the config file, and the position is well saved, but relative to the screen when it's closed.

If I change manually the x position to 2000 for example, it opens then in the scren 1 (that's fine!) but when I quit it saves the relative position to 80 for example, and then next time will open to x=80 but on screen 2 :-(

I'd be very happy if you can change this when gtk has corrected it ;-)

Take care of you and thanks again!
Sylvain

**Comment by giuspen** [comment] 2022-02-14 20:57
It's been fixed now in Gtk3 https://gitlab.gnome.org/GNOME/gtk/-/issues/4690 I'll release a new cherry tree version as soon as a new Gtk3 version including this fix is out

**Comment by paramecie** [comment] 2022-02-14 21:06
Grazie mille Giuseppe!

**Comment by giuspen** [comment] 2022-02-18 15:31
fixed in upcoming 0.99.46

**Closed by giuspen** 2022-02-18 15:31 UTC

**Comment by paramecie** [comment] 2022-02-18 15:34
Woo hoo! Will download and tell you. Thanks a lot!

**Comment by paramecie** [comment] 2022-02-19 14:57
Confirmed : works perfectly now!

I opened the file, it opened on screen 2, the incorrect one, moved the window to screen 1, close it.
Since then it opens on the right screen, screen 1 :+1: 

Tried a couple of others, no problem. In short, thanks for the FAST diagnostic/correction Giuseppe! Please have a nice weekend.

**Comment by giuspen** [comment] 2022-02-19 15:42
Cheers @paramecie have a good weekend 😉

**Comment by lmattcris** [comment] 2022-02-21 16:00
Well... would love to test it, but the main site looks to be down since this morning... 🤷‍♂️

**Comment by lmattcris** [comment] 2022-02-22 07:40
All OK now, well done 👍 
I'm using 0.99.46 on Win 11 pro right now
