### ISSUE TITLE
Cannot combine monospace and italic.

### ISSUE THREAD

**Issue by akwala** [giuspen/cherrytree#1308] opened 2020-11-02 00:58 UTC
**Version, Operating system**
CherryTree 0.99.18
Kubuntu 20.04

**Describe the bug**
Text formatting: Cannot combine monospace and italic.

**To Reproduce**
1. Enter text in a node/subnode.
2. Highlight the entered text, then do Ctrl-I or select from menu Formatting > Toggle Italic Property.
3. The highlighted text appears italicized.
4. With the same text highlighted, do Ctrl-M or select Formatting > Toggle Monospace Property.
5. The text appears in monospace font but it is no longer italicized.
6. ~~Behavior is the same if the order of the above formatting is reversed: the second formatting undoes the result of the first.~~ Starting with unformatted text, apply the above two format types in the opposite order, i.e., first make the text monospace, then try to italicize it.
7. The text that has been formatted as monospace will not get italicized.

Correct behavior would result in the text appearing in italicized monospace font in both cases

I tried various combinations of formatting. The only times I saw issues were when italic and monospace were combined. Specifically, formatting text as monospace removes and doesn't allow applying the italic format. Other formatting (bold, underline, etc.) behave correctly with monospace. E,g....
1. unformatted text --> format bold
2. same text --> format underline
3. same text --> format italic
4. the text is now bold, underlined and italicized
4. same text --> format monospace
5. result: text that is monospace, bold and underlined but not italicized.

**Screenshots**

**Comment by txe** [comment] 2020-11-02 12:27
what font is used for monospace? (Preferences dialog, Fonts -> Monospace)

**Comment by akwala** [comment] 2020-11-02 21:39
> what font is used for monospace? (Preferences dialog, Fonts -> Monospace)

Noto Mono Regular

**Comment by txe** [comment] 2020-11-03 12:15
I re-read again your issue description

> Behavior is the same if the order of the above formatting is reversed: the second formatting undoes the result of the first.

So if you apply monospace first and italic style second, then the text stop being monospace? Are sure?

**Comment by giuspen** [comment] 2020-11-03 12:36
I was thinking @txe maybe I'll add a checkbox to the custom font for the monospace since somebody does not seem to be happy with that because of the drawback of not being able to apply other styles on top of it

**Comment by txe** [comment] 2020-11-03 12:41
Maybe it is some misunderstanding. I don't have 'Noto Mono Regular', but I tried 'Noto Sans Mono Regular' and it worked pretty fine.

I had some issues with 'Monospace Regular' when font size was small and as result italic could not be noticed.
I'm not sure if the checkbox can help because this time monospace font was customize any way.

**Comment by giuspen** [comment] 2020-11-03 12:59
I see thanks @txe

**Comment by Hoffenbar** [comment] 2020-11-03 18:58
Sounds similar to # 1264 (monospace + bold)?

**Comment by txe** [comment] 2020-11-03 19:18
@giuspen , what if just remove the monospace font from dialog?)) Do you see any difference how it was before monospace font and now?

**Comment by giuspen** [comment] 2020-11-03 19:32
@txe not sure I understand, we want to let the user be able to set a custom monospace font if wanted (different than just the rich text one with tag monospace) but that could be optional with a checkbox and if untick all these issues would go.

**Comment by giuspen** [comment] 2020-11-03 19:33
I remember multiple requests for custom monospace font don't want to revert on that

**Comment by akwala** [comment] 2020-11-03 21:43
> I re-read again your issue description
> 
> > Behavior is the same if the order of the above formatting is reversed: the second formatting undoes the result of the first.
> 
> So if you apply monospace first and italic style second, then the text stop being monospace? Are sure?

Apologies. I've corrected the issue details.

> I don't have 'Noto Mono Regular', but I tried 'Noto Sans Mono Regular'

I didn't know both of these exist. Noto Mono Regular of course appears first during selection, and Noto Sans Mono Regular is waaay down after that. _Noto Sans Mono Regular behaves correctly with monospace_ – probably because there's a corresponding italic variety, while there isn't one for Noto Mono Regular, though that's not clear from what the font manager shows:
![Screenshot_20201103_161955](https://user-images.githubusercontent.com/1786/98042684-fa624480-1df1-11eb-8aa8-c4f9ff4874bc.png)
![Screenshot_20201103_162046](https://user-images.githubusercontent.com/1786/98042695-fe8e6200-1df1-11eb-951f-fc91081aed8c.png)

Testing with Fira Mono Regular and Fira Code Regular showed the same difference in behavior. Here it's clearer that Fira Mono Regular does _not_ have a corresponding italic variety but Fira Code Regular does.
![Screenshot_20201103_162305](https://user-images.githubusercontent.com/1786/98042722-0b12ba80-1df2-11eb-8ac2-f3483b60815a.png)

So, this doesn't seem to be an issue at all as long as one chooses a monospace font that includes all the varieties of formatting.

**Comment by txe** [comment] 2020-11-08 15:29
So, I suppose, the issue is resolved, closing

**Closed by txe** 2020-11-08 15:29 UTC

**Comment by akwala** [comment] 2020-11-12 23:50
Welllll... The bad behavior has returned, so [my inference above](https://github.com/giuspen/cherrytree/issues/1308#issuecomment-721389719) doesn't seem valid. (I've deleted the Noto Mono Regular font which seems non-standard.)

![cherrytree-fonts](https://user-images.githubusercontent.com/1786/99010346-d6041780-2517-11eb-8839-297d1916f7c0.png)

**Comment by txe** [comment] 2020-11-13 10:25
Try Noto Sans Regular (without Mono), it still will look as monospace font for monospace text (due to special tag inside the program)

**Comment by akwala** [comment] 2020-11-13 20:58
> Try Noto Sans Regular (without Mono), it still will look as monospace font for monospace text (due to special tag inside the program)

The UI does not present Noto Sans Regular as an option when selecting the monospace font.
![image](https://user-images.githubusercontent.com/1786/99120500-fc35c000-25c8-11eb-8b02-deae976e46f5.png)

**Comment by txe** [comment] 2020-11-13 21:08
@akwala , well, I mentioned that font because you could select it for Rich Text. Still, it doesn't matter, I meant you could choose any regular font (like Sans) and it would look like monospace font due to a special tag inside the program.

**Comment by akwala** [comment] 2020-11-13 21:54
> @akwala , well, I mentioned that font because you could select it for Rich Text. Still, it doesn't matter, I meant you could choose any regular font (like Sans) and it would look like monospace font due to a special tag inside the program.

Confused... I picked Sans Regular as the monospace font (there's no font named just Sans). With this, monospace formatting doesn't change the font, only changes the background color to that set for monospace text. And it still doesn't allow italics.

**Comment by giuspen** [comment] 2020-11-14 10:34
@akwala if you could deselect the use of a custom font for the monospace (legacy behaviour which would allow you to combine with other tags) would that solve your problem?

**Comment by akwala** [comment] 2020-11-14 20:44
> @akwala if you could deselect the use of a custom font for the monospace (legacy behaviour which would allow you to combine with other tags) would that solve your problem?

Couldn't find a way to do this in Edit > Preferences so I did this...
```
$ grep -i monospace ~/.config/cherrytree/config.cfg
monospace_bg=#eeeeec
monospace_font=Monospace 12
toolbar_ui_list=tree_add_node,tree_add_subnode,separator,go_node_prev,go_node_next,separator,*,ct_save,export_pdf,separator,find_in_allnodes,separator,handle_bull_list,handle_num_list,handle_todo_list,fmt_indent,fmt_unindent,separator,handle_image,handle_table,handle_codebox,handle_embfile,handle_link,handle_anchor,separator,fmt_rm,fmt_color_fg,fmt_color_bg,fmt_bold,fmt_italic,fmt_underline,fmt_strikethrough,fmt_h1,fmt_h2,fmt_h3,fmt_small,fmt_superscript,fmt_subscript,fmt_monospace
```
...and removed the line `monospace_font=Monospace 12` under `[colors]` in _~/.config/cherrytree/config.cfg_. This caused the monospace font to be set to Monospace Regular, size 9, and the behavior with italic was the same. Increasing the monospace font size in Edit > Preferences added back the line I deleted in ~/.config/cherrytree/config.cfg_.

**Comment by giuspen** [comment] 2020-11-14 21:27
It is not possible at the moment but I can add such option in the next version

**Comment by akwala** [comment] 2020-11-14 22:22
> It is not possible at the moment but I can add such option in the next version

Disabling custom font selection for monospace can only be a temporary workaround. This issue is a bug and should be re-opened. It needs to be prioritized like any other and fixed.
