### ISSUE TITLE
Future install on arch linux failing

### ISSUE THREAD

**Issue by kleshas** [giuspen/cherrytree#607] opened 2020-01-17 06:26 UTC
Using visual-studio-code-bin on arch. ctrl-shift-B to install when highlighting build.sh resulted in the following error:

Traceback (most recent call last):
  File "scripts/gresource_to_c.py", line 46, in <module>
    sys.exit(main(sys.argv))
  File "scripts/gresource_to_c.py", line 34, in main
    file_Element.text = cgi.escape(os.path.basename(svg_filepath))
AttributeError: module 'cgi' has no attribute 'escape'
The terminal process terminated with exit code: 1

**Comment by giuspen** [comment] 2020-01-18 14:38
I'll try myself soon, looks like a python version issue

**Comment by kleshas** [comment] 2020-01-21 05:24
I built it using the arch instructions, rather than using vs code.  Seemed to install fine, but got this error running: 
cherrytree:70189): glibmm-CRITICAL **: 21:22:37.337: 
unhandled exception (type Glib::Error) in signal handler:
domain: gtk-css-provider-error-quark
code  : 1
what  : <data>:1:58not a number

Segmentation fault (core dumped)

**Comment by giuspen** [comment] 2020-01-21 21:44
I would not advise to install the Gtkmm3 version for now but just build and run locally for testing. Can you try and give me some more info reproducing the crash while debugging in Visual Studio?

**Comment by kleshas** [comment] 2020-01-21 22:47
OK, redownloaded, rebuilt then run the debugger.
Breakpoint 1, main (argc=1, argv=0x7fffffffe7b8) at src/ct/ct_main.cc:25    is the first error line, then this at the bottom:

Thread 1 "cherrytree" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d2a8a4 in Gtk::TextBuffer::get_iter_at_offset(int) () from /usr/lib/libgtkmm-3.0.so.1

**Comment by giuspen** [comment] 2020-01-23 08:05
it seems a real issue but I cannot reproduce it at the moment and it's anyway early now since I still have to change a lot, let's pause it for now and get back to it later...

**Comment by txe** [comment] 2020-08-25 17:09
Closing, building future version shouldn't be issue now.

**Closed by txe** 2020-08-25 17:09 UTC
Labels: topic: install\running\future
