### ISSUE TITLE
Feature Request: Applications Links

### ISSUE THREAD

**Issue by bitboy85** [giuspen/cherrytree#301] opened 2017-11-27 15:17 UTC
In the Hyperlink menu there are currently the possibilities to add a file, Folder or a Webseite. It would be glad to have a fourth Option to use "application links" like "mailto:" to open a mailprogram or "tel:" to open a phone app.

**Comment by giuspen** [comment] 2021-03-01 22:25
duplicate of #1082

**Closed by giuspen** 2021-03-01 22:25 UTC
Labels: enhancement
