### ISSUE TITLE
Adjust text and tree default size if tree on the right option is selected

### ISSUE THREAD

**Issue by morciej** [giuspen/cherrytree#815] opened 2020-05-18 21:01 UTC
When **Preferences > Tree 2 > [ V ] Display Tree on the Right Side** is toggled, initially tree gets displayed in correct column width. However, after closing to tray, and reopening, the tree shows on the correct side, but column width for it did not get corrected, so tree displays wide, and text narrow, in the usual case.

Expected behaviour: new column widths for text and table get saved and restored correctly when changing the option and then closing window to tray.

Work-around: save the file immediately after changing the "Display Tree on the Right Side" option toggle, and then exit CherryTree. After opening, tree is displayed with the correct width, and restore from tray works correctly.

Solution: Correctly record changed column width after "Display Tree on the Right Side" has been toggled by user.

System: Toshiba Satellite L300, 3GB RAM, LinuxMint 19.1 (tessa), XFCE, CherryTree ver. 0.37.6

**Comment by giuspen** [comment] 2020-05-19 16:59
Hi can you add the version you are using and the operative system?

**Comment by morciej** [comment] 2020-05-19 18:15
Added info to post.

**Comment by giuspen** [comment] 2020-05-19 18:25
Please add the PPA https://launchpad.net/~giuspen/+archive/ubuntu/ppa so that you upgrade to the latest version and report if the issue is still there

**Comment by txe** [comment] 2020-06-16 10:04
Closing cause the issue is related to the old version

**Closed by txe** 2020-06-16 10:04 UTC

**Comment by morciej** [comment] 2020-08-16 18:07
I added the PPA and updated. Not corrected yet in Cherrytree ver. 0.39.4

**Comment by giuspen** [comment] 2020-08-16 19:14
With new version we mean the 0.99.x https://www.giuspen.com/cherrytree/#testing

**Comment by morciej** [comment] 2020-12-08 19:06
OK thanks.
