### ISSUE TITLE
export as pdf, the picture is blurry

### ISSUE THREAD

**Issue by linpxin** [giuspen/cherrytree#420] opened 2018-11-04 15:30 UTC
well, I am using cherrytree v0.38.6 in windows10 x64. When I export the cherrytree document as pdf, the picture is blurry. Does it have any options to adjust the quality of picture?

_Sent from my 8692-M02 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by giuspen** [comment] 2018-11-05 13:52
There are no options, with the current toolkit in use (pygtk2) this is the best result

**Comment by linpxin** [comment] 2018-11-05 15:19
that sucks

_Sent from my 8692-M02 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by bitboy85** [comment] 2019-04-14 12:28
Seems to be a duplicate of https://github.com/giuspen/cherrytree/issues/119

**Closed** 2020-02-09 19:58 UTC
