### ISSUE TITLE
Feature Request: Add Ability to Scroll Past End of Line

### ISSUE THREAD

**Issue by wolfbyte** [giuspen/cherrytree#398] opened 2018-08-29 15:43 UTC
Problem:
Would like to be able to keep scrolling past the end of a document. 

Reason:
Editing on the bottom lines of a document just feels wrong and bothersome. I would prefer to be editing in the middle of the screen. Less strain on neck. I know it's simple, but the feature in Notepad++ has really made the entire editing experience a lot more comfortable.  I think the same feature in CherryTree would be incredible. 

Similar Feature:
Notepad++ allows for a similar feature. Settings -> Preferences -> Editing -> Check Enable Scrolling beyond last line

**Comment by giuspen** [comment] 2018-09-01 09:02
This seems to be impossible with gtk2 but hopefully I'll find a way after port to gtk3, I also need this feature that I find useful in geany ide

**Comment by hb20007** [comment] 2019-08-20 11:04
Duplicate of #109

**Comment by txe** [comment] 2020-09-15 20:37
Resolved by #1162 for C++ version, Edit->Preferences->Text and Code-> [] Scroll Beyond Last Line

**Closed by txe** 2020-09-15 20:37 UTC
Labels: enhancement
