### ISSUE TITLE
[0.38.0] Cherrytree inserts lots of space characters in copy&pasted text.

### ISSUE THREAD

**Issue by kettenfett** [giuspen/cherrytree#233] opened 2017-03-03 09:39 UTC
When copy & pasting text from the internet (I tested Firefox 51.0.1 32bit), Cherrytree inserts a lot of space chars. One every 50 to 70 chars. It is never inside a word, always adjacend to other spaces. So this leads to double spaces and can easily be searched for. 

The following is a text I copy and pasted from wikipedia (https://en.wikipedia.org/wiki/Commonwealth_Games) into Cherrytree and then find & replaced double spaces with double underscores plus a linebreak, to visualize them better:

``The` first edition of the event was the 1930 British Empire Games __

11 nations participated. The quadrennial schedule of the games was__

interrupted by the Second World War and the 1942 Games (set to be held in Montreal) and the 1946 Games were abandoned.[5]__

The games were revived in 1950 and underwent a name change four years__

later with the first British Empire and Commonwealth Games in 1954.[1] Over 1,000 athletes participated in the 1958 Games as over thirty teams took part for the first time.[6]
The 1978 Games in Edmonton marked a new high as almost 1,500 athletes from 46 countries took part.[6] They were boycotted by Nigeria, in protest of New Zealand's sporting contacts with apartheid-era South Africa, as well as by Uganda, in protest of alleged Canadian hostility towards the government of Idi Amin.[7]__

Participation at the 1986 Games was affected by a boycott by 32__

African, Asian and Caribbean nations in protest of British Prime__

Minister Margaret Thatcher's__

refusal to condemn sporting contacts of Apartheid era South Africa in__

1985, but the Games rebounded and continued to grow thereafter. The 1998__

Commonwealth Games in Kuala Lumpur, Malaysia saw the sporting programme__

grow from 10 to 15 sports as team sports were allowed for the first time.[1]__

Participation also reached new levels as over 3500 athletes represented__

70 teams at the event. At the Games in Melbourne in 2006, over 4000__

athletes took part in sporting competitions.[6]
The three nations to have hosted the games the most times are__

Australia (5), Canada (4) and New Zealand (3). Furthermore, six editions__

have taken place in the countries within the United Kingdom (Scotland__

3, England 2 and Wales 1), twice in Asia (Malaysia 1 and India 1) and__

once in the Caribbean (Jamaica 1). Two cities have held the games on__

multiple occasions: Auckland (1950 and 1990), and Edinburgh (1970, 1986__

and some events in 2014).
The first Commonwealth Paraplegic Games were held alongside the Commonwealth Games from 1962 to 1974.[8] Athletes with a disability were then first included in exhibition events at the 1994 Commonwealth Games in Victoria, British Columbia,[9]__

and, at the 2002 Commonwealth Games, they were included as full members__

of their national teams, making them the first fully inclusive__

international multi-sport games. This meant that results were included__

in the medal count.[10]`_

**At first I thought, this probably occurs at line breaks in the original text, but this is not the case. I tried to find out some sort of pattern that dictates, when Cherrytree inserts a space, but I couldn't find one. 
The only thing I noticed, is that it doesn't happen with text from raw html sites like this one:**

http://www.geography.hunter.cuny.edu/~jochen/GTECH361/lectures/lecture10/3Dconcepts/Getting%20information%20from%20rasters.htm

**I had this happen with text from other sources too, not just wikipedia.
When I first paste the text into notepad++ and then into Cherrytree, there are no double spaces, so this is clearly a problem with Cherrytree.**

**Comment by mofo1** [comment] 2017-04-05 13:59
I can confirm this happens on Windows 10 with CherryTree since at least ver 32.0. I've used it to copy and paste text using notepad, Word 2013, and Word 2016 and CherryTree will (seemingly) randomly insert 2 spaces between words every so often. No idea why it happens.

**Comment by txe** [comment] 2020-10-29 22:09
Fixed in 0.99

**Closed by txe** 2020-10-29 22:09 UTC
Labels: topic: clipboard, usability
