### ISSUE TITLE
[0.99.6-1.deb] Color file-picker

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1030] opened 2020-07-22 16:47 UTC
The color file-picker icon which is proposed in the font custom color panel has no effect, at least in linux/KDE.
Then maybe better remove it until problem identified ?  (...not a key feature).

**Comment by ForeverRainbow** [comment] 2020-07-24 08:40
See: #896 its not yet implemented

**Comment by ciranus** [comment] 2020-07-24 12:12
It does not look obvious at all that #896 has something related to a **color-picker** feature, but if you mean the root cause is the same, it's fine, we'll see.
Let's say... to be confirmed.

**Comment by ForeverRainbow** [comment] 2020-07-24 15:29
Ah right sorry, didnt realize what you meant. I would guess they have the same root cause of not being implemented as part of the whole theme stuff yet

**Comment by txe** [comment] 2020-07-27 10:55
The screenshot is really helpful. This color-picker feature exists only on KDE systems, on XFCE/linux or windows there is no such button. 
So far, I could manage to find something about the issue on [kubuntu forum](https://www.kubuntuforums.net/showthread.php/76021-Gimp-2-10-8-color-picker-issue). I don't see any options to turn it off or fix it.

**Comment by ciranus** [comment] 2020-07-27 12:53
If it can help later, this is the message I get:

```
(cherrytree:6457): Gtk-WARNING **: 14:50:02.254: Attempting to add a widget with type gtkmm__GtkColorChooserDialog to a gtkmm__GtkApplicationWindow, but asa GtkBin subclass a gtkmm__GtkApplicationWindow can only contain one widget at a time; it already contains a widget of type gtkmm__GtkVBox
[2020-07-27 14:50:02.254] [GTK Logger] [warning] This object, of type gtkmm__GtkColorChooserDialog, already has a wrapper.
You should use wrap() instead of a constructor.
```

Just in case it can help later on.
Minor issue.

**Comment by txe** [comment] 2020-07-27 16:22
Yeah, thanks,
Actuall

**Comment by txe** [comment] 2020-07-27 16:32
Yeah, I took a look at other warnings in console, the important one is 
```the GVariant format string '(u)' has a type of '(u)' but the given value has a type of '((u))'```

Actually, GIMP uses controls similar to Gtk and had [the same issue](https://gitlab.gnome.org/GNOME/gimp/-/issues/1878) and [the fix](https://github.com/GNOME/gimp/commit/b29d1ea6ff0dec77cfd206049ef88353e09abbe0) for it.

There is the same problematic place `g_variant_get (retval, "(u)", &color);` in [Gtk code](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkcolorpickerkwin.c#L135).
So, you take this data and create an issue on https://gitlab.gnome.org, then it can be easily fixed by them.

**Comment by ciranus** [comment] 2020-07-27 17:36
Hummm... in fact I've never used gnome, and don't use gimp at all.
I am not sure to be very welcomed @ gitlab.gnome.org as a KDE user.
From my point of view, this is minor, it was just a warning in case of potential interest.
I even don't know what this color-picker is supposed to open, and totally don't understand how this icon can be visible in KDE environment only.
It's all I can do to help on that one. You can re-close this issue if you want !

**Comment by txe** [comment] 2020-07-27 17:44
gnome will welcome it:
- code from `gtkcolorpickerkwin.c `, kwin` means KDE windows, so it's a widget specially made for KDE window system.
- they don't a lot of people to test and then to fix issues, so to get an issue and the fix for it (to change a couple of symbols) at once should be appreciated.

But it's up to you, closing this.

**Closed by txe** 2020-07-27 17:44 UTC
