### ISSUE TITLE
Menu has dark blue highlights on black text

### ISSUE THREAD

**Issue by vatterspun** [giuspen/cherrytree#157] opened 2016-07-02 17:45 UTC
Setup: Win7x64

Steps:
1. Start program (tested both 0.36.9 and 0.37.1)
2. Open menu and hover item over menu text

Defect: Dark colors on top of black text make menus difficult to read.

Screenshot: http://i.imgur.com/HeNWjE1.png

This was also an issue on the previous version.

**Comment by Fixer-007** [comment] 2016-07-02 23:39
Ugh, thats infamous GTK theme when `windows classic theme` is used in Windows, I've seen this ugliness for years in many programs, GTK people does not care apparently.

**Comment by Maxol** [comment] 2019-02-13 15:51
FIRST OF ALL: I love CherryTree! I like CherryTree so much I decided to join and help improving the software. So here is my first contribution...

I have the same problem on Windows 7 as you can see in image A below. After some testing I found out that it is not caused by a theme. However, the theme shows us very clearly that CherryTree has not implemented the system colors properly.

If you go to the [Window Color and Appearance] dialog (B) you can change the color of various elements. I picked the [Selected Items] under [Item:]. This is the setting that specifies the colors for the selected menu items. I changed the background color to red and the foreground color to yellow. This resulted in a readable menu in CherryTree (C). But...as you can see the text color is still dark - not yellow - where all my other programs adopted the yellow in their menus (D).

So CherryTree probably uses a hardcoded dark color where it should use the dynamic system color for the highlighted menu background.

![Menu Problem in CherryTree](http://orangegild.com/images/github/CherryTree01.png)

**Comment by txe** [comment] 2020-10-29 21:08
I suppose it fixed with Gtk3 which uses a custom theme instead of emulating windows one.

**Closed by txe** 2020-10-29 21:08 UTC
Labels: os: win, usability
