### ISSUE TITLE
[0.37.6] Copy&pasted text from websites via clipboard has white background.

### ISSUE THREAD

**Issue by philippHRO** [giuspen/cherrytree#223] opened 2017-01-29 18:35 UTC
Selecting text on almost any website and copy&pasting it into Cherrytree get's a white backgrond (see images). This is very annoying, because usually you just want the text. It's especially annoying, when the dark cherrytree theme is used.

![image](https://cloud.githubusercontent.com/assets/23098362/22406800/caeb563e-e659-11e6-97e4-fc9a61ca1f97.png)
Selecting text from wikipedia.

![image](https://cloud.githubusercontent.com/assets/23098362/22406795/c26f54e2-e659-11e6-9994-d95bf8522afa.png)
Pasting into Cherrytree. Text has white background. Grrrr...

**Comment by giuspen** [comment] 2017-01-29 19:23
please try http://www.giuspen.com/topic/0-38-release-candidate-2/ and if the problem is confirmed write an url where to copy text from

**Comment by philippHRO** [comment] 2017-01-29 19:40
It's still the same. This time I just copied some text from the thread (http://www.giuspen.com/topic/0-38-release-candidate-2/).

And also from wikipedia (https://en.wikipedia.org/wiki/Titchwell_Marsh)

![image](https://cloud.githubusercontent.com/assets/23098362/22407218/8c8fd4ba-e662-11e6-91cc-370c811aed7d.png)

![image](https://cloud.githubusercontent.com/assets/23098362/22407244/1465cf02-e663-11e6-9930-6c3a63fcfe9b.png)

**Comment by giuspen** [comment] 2017-02-09 00:57
should be fixed in https://github.com/giuspen/cherrytree/commit/dd841863ed7832951096ff34e51de988c12d84e5

**Closed** 2017-02-26 23:22 UTC
