### ISSUE TITLE
Checkbox Bug: CTRL+SPACE doesn't cycle through available mark choices

### ISSUE THREAD

**Issue by NouGithub** [giuspen/cherrytree#1775] opened 2021-08-15 18:02 UTC
Ubuntu 18.04.5 + Cherrytree 0.99.40

Ctrl+SPACE on checkboxes only adds a **Checkmark**, it will not continue cycling through produce a **Cross** or a **Default Empty Box**.

Using Ctrl+Alt+3 to create a checkbox, then hitting Ctrl+SPACE to cycle through the mark types: only produces a checkmark and stops there.

Tried changing fonts and sizes to fix this.  Did not work.
Tried clicking the box, and this also only produces a checkmark and stops there.
Confirmed that the three available mark-types are present in the settings.

Thank you

**Comment by giuspen** [comment] 2021-08-28 14:48
The ppa is the best option actually. If you confirm that you can reproduce the issue on an empty rich text node where the only content added is the todo list item, then I'll see if I can reproduce on a 18.04 virtual machine

**Comment by NouGithub** [comment] 2021-08-28 14:53
Hi,

I just created a new and empty ctb file and inserted a to-do item via Crtl-Alt-3; Ctrl-Space adds a checkmark, then doesn't do anything else upon further strokes of Ctrl-Space.  

Are there any kinds of debug logs that I could send that may help?

Thank you again

**Comment by giuspen** [comment] 2021-08-28 15:05
if you run from a terminal, see messages printed out but nothing indicating a failure when the bug happens it means that the log won't help. I need to try on an 18.04 and see if it happens for me too there. If you would have another PC and confirm if it happens there too or not it would help

**Comment by NouGithub** [comment] 2021-08-28 15:23
The only other PC I have is windows -- and it works there (for what that's worth).  Sorry, I know that's not helpful.

**Comment by giuspen** [comment] 2021-08-28 15:26
It turns out I can reproduce it on the 18.04 VM, I'll have a look

**Comment by NouGithub** [comment] 2021-08-28 15:27
Thank you -- that is the best news I've had all day!

**Comment by giuspen** [comment] 2021-08-28 22:13
fixed in next version 0.99.41

**Closed by giuspen** 2021-08-28 22:13 UTC

**Comment by NouGithub** [comment] 2021-08-28 22:52
Thank you, sir!
