### ISSUE TITLE
CherryTree 0.99.20: search and node issue

### ISSUE THREAD

**Issue by 1Martinik** [giuspen/cherrytree#1337] opened 2020-11-15 15:09 UTC
I have tested the CherryTree 0.99.20 on my Windowss 10 x64 and I would like to share with you my findings when using my 600MB .ctb database file.
CherryTree crashes in the following situations:
- when use search: no matter what you are searching
- I have created a node with all information found here https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt. When reopen the cherry tree and click on this node the program is craching without showing the node content.

This is the event log
Faulting application path: C:\Program Files\CherryTree\mingw64\bin\cherrytree.exe
Faulting module path: C:\Program Files\CherryTree\mingw64\bin\libgtk-3-0.dll

P.S.
On Kali Linux 2020.1 I have CerryTree 0.38.8 and it works perfect.

**Comment by ylaizet** [comment] 2020-11-20 13:56
Hello, same issue, any search crashes cherrytree : ubuntu 20.04, cherrytree 0.99.21.

Here is the error:
`[2020-11-20 14:53:38.328] [gtk] [info] 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_M_construct null not valid

Trappe pour point d'arrêt et de trace (core dumped)`

**Comment by txe** [comment] 2020-11-20 19:28
I couldn't reproduce the issue. If you can provide or create a cherrytree document as an example, the issue will be resolved instantly.

**Comment by ciranus** [comment] 2020-11-20 21:50
@1Martinik was referring to a 600MB .ctb database file, then probably difficult to reproduce same condition.

**Comment by giuspen** [comment] 2020-11-22 15:58
You are mentioning Kali Linux, can you reproduce it there with 0.99.21?

**Comment by 1Martinik** [comment] 2020-11-22 17:20
CherryTree 0.99.21 compiled and tested on Kali Linux 2020.1

Search issue:
No changes. It still crashes.

Node issue:
It takes too much time to load the node content: about 1 minute. The old version (CherryTree 0.38.8) is faster, about 1 second max.
After loading the big node, the CherryTree 0.99.21 is freezing. It can be closed by killing the process.

The old version (CherryTree 0.38.8) is more reliable on Kali Linux 2020.1

**Comment by giuspen** [comment] 2020-11-22 17:53
This is actually good news because if you reproduce it also on Linux it will be easier to track down and fix. If you run it from a terminal and reproduce the issue, do you see anything printed out that could help us figure out what's going on?

**Comment by 1Martinik** [comment] 2020-11-22 18:57
Tested again and ran it from terminal.
No errors received in terminal.
The only thing that I've noticed is that it is using 2GB of memory.

**Comment by giuspen** [comment] 2020-11-22 19:53
You mentioned creating a (huge) node with the content from that link, if you create a brand new document with only that node is it also crashing?

**Comment by 1Martinik** [comment] 2020-11-22 20:16
I have created a new .ctb database with one subnode.
When paste all content from http://www.securityspace.com/smysecure/daudit_ports.html, it freezes.

**Comment by giuspen** [comment] 2020-11-22 20:31
I appreciate that you raise all the issues that you found on the way but that of pasting html should go to a new issue.
Let's focus on the crash during the search here, please help me fix that here.
Please @1Martinik or @ylaizet send me privately a document via mail (or put to google drive and share the link privately with me) I promise I'll burn the document to ashes as soon as I fix this issue.

**Comment by ylaizet** [comment] 2020-11-26 18:02
HI, I tried to export a node into a new database to give you an example to reproduce the bug and actually I couldn't. Exporting crashes as well leaving an empty ctb file.
```
[2020-11-26 17:36:37.780] [   ] [debug] /home/xxxxx/.config/cherrytree/config.cfg parsed
[2020-11-26 17:36:37.922] [   ] [debug] autosave is started
[2020-11-26 17:36:38.127] [   ] [debug] Node name: xml
[2020-11-26 17:36:38.418] [   ] [debug] Node name: xml
[2020-11-26 17:36:40.512] [   ] [debug] Node name: Flym
[2020-11-26 17:36:41.497] [   ] [debug] shift images in MenuBar/context menu
[2020-11-26 17:36:55.135] [gtk] [info] 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_M_construct null not valid

Trappe pour point d'arrêt et de trace (core dumped)

```
Then I tried to to copy paste a few information nodes into a new (instance), saved it successfully. With this new ctb file, searching works perfectly.

Finally, by deleting each node one after the other, I narrowed down the issue to a node that was crashing cherrytree just by clicking on the node to display it. I observed that this node had an image in the image table. If I remove the entry from the image table, everything works well. It looks like displaying the image or searching (then probably hitting the node containing the image) cause the crash.

**Comment by giuspen** [comment] 2020-11-26 19:25
Can you share this single node database that crashes?

**Comment by 1Martinik** [comment] 2020-11-26 20:22
Hello,
I extracted 2 nodes from my database and you can use them to test both problems regarding the application crash:
- on search
- view subnode
I've tested on CherryTree 0.99.22.0 and the problem still exists.

https://wetransfer.com/downloads/8718b224bc165d830ee4db18e1c8738120201126201621/be6a81ea11c0abff3001f146bb0e61e820201126201654/762d45

**Comment by giuspen** [comment] 2020-11-26 21:11
it is a good test case thanks, I can see cherrytree freezing, apparently because of the large table, something I'll work on shortly

**Comment by ylaizet** [comment] 2020-11-27 08:58
Hi, here my image example bug case:
https://we.tl/t-NDROZKzygE

**Comment by giuspen** [comment] 2020-11-28 21:37
@ylaizet thanks I can see the problem with your document as well

**Comment by giuspen** [comment] 2020-11-29 14:00
The issue of @ylaizet will be fixed in 0.99.24 while that of 1Martinik may take a bit longer

**Comment by joejac** [comment] 2021-06-06 00:53
Hello, I confirm this issue, it crashes on _search in the content of all nodes_, but it works on _search in the name and tags of nodes_.
My Database is 901 MB.
Tested on: 
1. CheryTree Version: 0.99.37 running on Flatpak in MX Linux 19.3
2. CheryTree Version: 0.99.37 running on Lubuntu 20.04
Regards

**Comment by giuspen** [comment] 2021-06-07 21:13
@joejac it is likely that the crash happens when parsing one exact node.
Since your db is very large, maybe you can repeat more searches on different nodes and subnodes to identify at least a subset of the database that make it crash, so maybe you can export that few nodes only as a new cherrytree document and send me privately so that I can reproduce the issue

**Comment by joejac** [comment] 2021-06-08 17:29
> @joejac it is likely that the crash happens when parsing one exact node.
> Since your db is very large, maybe you can repeat more searches on different nodes and subnodes to identify at least a subset of the database that make it crash, so maybe you can export that few nodes only as a new cherrytree document and send me privately so that I can reproduce the issue

Hello Giuseppe and thanks for the information.
1. With the function search on node and subnodes (Control Alt F) I finally found the problematic node, is number 445. CherryTree is unable to export the node and its sub-nodes, it crashes.
2. I used SqliteBrowser, found the node in the **node** table, and exported the **binary**, I do not know if it helps in order to find the problematic characters, please download it and let me know what is wrong with the content of such node, thank you for your help.
Regards
https://pad.garudalinux.org/file/#/2/file/eo5Wk-fLtmHtggjxFn273vee/

**Comment by giuspen** [comment] 2021-06-08 17:47
Since you found the problematic node please do the following: copy and paste your database file .CTB
Then open the copy and delete everything except that node, then send me the cherrytree document with the node with the problem

**Comment by joejac** [comment] 2021-06-08 19:39
Hello, there are only 4 text notes on the tree, after deleting all the rest, but unfortunately, the ctb file is 422,8 megabytes.
I exported the tree to Cherrytree and it is only 40 Kbytes but it does not open, CherryTree crashes. This is the link to the exported file, hope this helps:
https://pad.garudalinux.org/file/#/2/file/N-+MIslI0F8RXvZOsCoTRCJz/

**Comment by giuspen** [comment] 2021-06-08 20:17
Thanks @joejac I'll try shortly and get back

**Comment by giuspen** [comment] 2021-06-08 21:57
the downloaded file is not opening because the database is incomplete
![image](https://user-images.githubusercontent.com/6842059/121262899-c336a300-c8ac-11eb-85a9-305bf41dd791.png)
the ctb file that you say is still 422.8 MB, if you try to File--"save and vacuum"?

**Comment by joejac** [comment] 2021-06-08 22:44
Hello Giuseppe and thanks for your time.
When I ended deleting almost all nodes and only 4 small nodes with only text remained, the ctb file was 770MB, I noticed the option "Save and vacuum" ("Guardar y compactar" in Spanish) and when it ended I got a ctb file of 422 MB, this is not logical. 10 minutes ago I did again "Save and vacuum" and I still have a 422 MB ctb file, my internet connection is too slow and my pad space is 50MB. Any other suggestions?
![Only4textnotes](https://user-images.githubusercontent.com/11170915/121266915-5827a500-c889-11eb-846e-f0e84ab739c9.jpg)

**Comment by giuspen** [comment] 2021-06-08 23:02
can you try to compress to .tar.xz? let's see how smaller it gets.

**Comment by joejac** [comment] 2021-06-09 01:16
Hello, This is the file, please let me know when you have downloaded it, thanks and good night.
http://topstyleart.com/tmp/CT4nodes.ctb.tar.xz

**Comment by giuspen** [comment] 2021-06-09 18:01
I have it now thanks, I think also if you have a google drive you can upload there and then create a shareable link for a single item

**Comment by giuspen** [comment] 2021-06-09 18:04
Great I can reproduce the crash, I'll work on this shortly

**Comment by joejac** [comment] 2021-06-09 19:08
> Great I can reproduce the crash, I'll work on this shortly
Ok I am glad you got it. Please also check why saving only 40 kilobytes of data, to a new name, Cherrytree creates a ctb file of 422MB?. Thank you and regards.

**Comment by giuspen** [comment] 2021-06-09 22:06
I fixed the problem and doing a file--save as of your document now it creates a new document of only 3.4 MB. I'll release 0.99.38 one of the next few days, maybe already tomorrow

**Closed by giuspen** 2021-06-09 22:06 UTC
