### ISSUE TITLE
Finder (Mac OSX) cannot open Cherrytree files

### ISSUE THREAD

**Issue by furest** [giuspen/cherrytree#1106] opened 2020-08-11 21:15 UTC
When opening a file from cherrytree on OSX, the files are greyed out.
Though as we can see the file type selected is "CherryTree Document"

OSX Version : 10.15.6
Cherrytree version : commit 0c1ba92 (latest at the time of this issue)

I'm not 100% sure whether this comes from my computer of from cherrytree itself. Maybe someone else compiling from sources can tell?

![image](https://user-images.githubusercontent.com/6944894/89949334-093cbf00-dc28-11ea-844d-59491f9a0403.png)

**Comment by ciranus** [comment] 2020-08-11 21:42
The cause can be the default gtk3 theme on your system
Can you try with a different one on you system ?
(I don't know macOs, but answer based on linux experience).
https://www.opendesktop.org/c/1300313

**Comment by giuspen** [comment] 2020-08-12 12:54
Is it preventing you to click on the grayed out lines at all or it is just the theme color?

**Comment by khaled-su** [comment] 2020-08-13 05:11
Same issue here. CherryTree documents in the open menu are non clickable on macOS.

**Comment by furest** [comment] 2020-08-15 14:28
I cannot select the files nor can I click the "open" button.
I'm not using any particular skin, just the dark theme of mac os.

However I think this is a newer bug (can't really tell when it began). I remember the firsts releases of Cherrytree that supported OS X compilation didn't have this problem...

**Comment by txe** [comment] 2020-08-15 14:30
The file/folder dialogs were replaced by "native" versions recently, it should be the cause.

**Comment by txe** [comment] 2020-08-15 15:53
Fixed by #1111
@furest , btw do you like more the new file-open dialog or the old one from previous versions?

**Closed by txe** 2020-08-15 15:53 UTC

**Comment by furest** [comment] 2020-08-15 17:56
Honestly it's not a menu I opened very often so I can't compare the two. The system dialog does the job just fine.
