### ISSUE TITLE
Ctrl+C shortcut for copying not working properly within tables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#29] opened 2015-03-22 22:19 UTC
```
What steps will reproduce the problem?
1. create a new table, write some content in a cell
2. select the content and use Ctrl+C to copy it
3. then try to put it somewhere else using Ctrl+V

What is the expected output? What do you see instead?
I expect to see the copied content of the cell reproduced, instead it will 
create a copy of whatever string was in the clipboard buffer before 

What version of the product are you using? On what operating system?
0.35.6, Windows 7

Please provide any additional information below.
If I use mouse right click + copy from the menu on the selected cell's content 
it works correctly.

```

Original issue reported on code.google.com by `liandrin...@googlemail.com` on 27 Jan 2015 at 3:30

**Comment by basil-twisleton** [comment] 2018-10-18 08:37
I see same/similar issues in v 0.38.6 on Win 10.

If I highlight the contents of a cell in a table as soon as I press ctrl it clears the selection, and thus when c is presses no new data is copied to the clipboard.

If I right-click and copy it works. 

Super easy to reproduce (and hopefully as easy to fix)

1. Add New Node
2. Insert table (any size)
3. Enter data in a field
4. highlight data
5. press ctrl 

At step 5 you will see that the text is no longer highlighted. 

If you need anything else, let me know.

**Comment by giuspen** [comment] 2018-10-22 05:14
Cannot reproduce on Ubuntu, seems to be a pygtk2 Windows issue

**Comment by txe** [comment] 2020-07-27 16:42
Closing, it's not actual with gtkmm version

**Closed by txe** 2020-07-27 16:42 UTC
Labels: bug, os: win, topic: clipboard
