### ISSUE TITLE
CherryTree startup from reboot/turn on (PC) without the configured theme and without loading the last notebook.

### ISSUE THREAD

**Issue by bahtioraliev** [giuspen/cherrytree#1581] opened 2021-03-30 08:16 UTC
**Version, Operative system**
- Linux
- Linux version 5.8.0-48-generic
- 54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021
- Desktop
- CherryTree 0.99.33
- Installed from apt

**Describe the bug**
CherryTree startup from reboot/turn on (PC) without the configured theme and without loading the last notebook.

**To Reproduce**
1. Create nookbook 
2. reboot or turn off > turn on 
3. You will get a blank menu

**Comment by giuspen** [comment] 2021-04-03 19:33
This should be fixed in upcoming 0.99.34. The problem is that at reboot, with cherrytree left running, cherrytree is being killed rather than normally closed, so it was not saving the configuration. Now cherrytree is saving the configuration **also** when being gracefully killed (SIGTERM) while nothing can be done in case of  immediate kill (SIGKILL) that anyway should not happen before a timeout in any operative system.

**Closed by giuspen** 2021-04-03 19:33 UTC

**Comment by bahtioraliev** [comment] 2021-04-04 08:04
@giuspen Thank you very much. Waiting for the next version to update.
