### ISSUE TITLE
Search List - Click on Results - do not jump to matching Line

### ISSUE THREAD

**Issue by puresse** [giuspen/cherrytree#2361] opened 2023-09-29 15:32 UTC
**Version, Operative system**
Linux Mint Focal

**Describe the bug**
when performing a Search (search on one tree page or all tree pages)
Result List - Click on any Line in the Results - there is no jump to matching Line or matching tree+result-line happening

**To Reproduce**
perform search over a tree page with a couple of occurrences of a word. no scrolling to the exact line happens when klicking on a result in the search results box.

**Comment by puresse** [comment] 2023-09-29 15:47
Can please point me someone to the previous version - the working .deb package - i need the search feature working... i'm using linux mint 20.1 which is Ubuntu 20.04 LTS,  (Focal Fossa)

thank you so much

**Comment by alhimik8** [comment] 2023-09-30 09:39
Version: 1.0.2-2, Linux Mint Focal, PPA

**Describe the bug**
When I use
Search - Find in multiple nodes
I get results, but when I press on any of them nothing happens. 
Before that I could go directly to that result in tree and see it in the node text.

**To Reproduce**
Search -> Find in multiple nodes
Type any text to find
(Default search settings)
Press on any of results when search ends

**Comment by alhimik8** [comment] 2023-09-30 09:39
> Can please point me someone to the previous version - the working .deb package - i need the search feature working... i'm using linux mint 20.1 which is Ubuntu 20.04 LTS, (Focal Fossa)
> 
> thank you so much

Compiled previous version (1.0.1) from git as was described in https://github.com/giuspen/cherrytree#building-cherrytree-on-ubuntu
But I think you can just use AppImage release file - https://github.com/giuspen/cherrytree/releases/tag/1.0.1 or use older snap version 0.99...
Before the bug will be fixed and we can use updated deb version as usual.

**Comment by gimplyworxs** [comment] 2023-10-02 09:39
same here ...
Linux Mint 20.1 MATE
hope it will be fixed soon

**Comment by giuspen** [comment] 2023-10-04 17:52
The quickest thing as @alhimik8 says is run the AppImage of 1.0.1 from https://github.com/giuspen/cherrytree/releases/tag/1.0.1
I'll have a look ASAP

**Comment by giuspen** [comment] 2023-10-04 20:59
I've been told that this issue appears on Linux Mint based on Debian 11/Ubuntu 20.04 while it does not on Linux Mint based on Debian 12/Ubuntu 22.04 (a user just upgraded LMDE 5 Debian 11 -> LMDE 6 Debian 12 and told me the issue has gone).
I haven't been able to reproduce it on my Ubuntu 20.04 (non Mint-ed).
I will try Debian 11 shortly, if I still cannot reproduce I will try and get hold of an older Linux Mint (I do have Mint but only the latest based on 22.04).

**Comment by giuspen** [comment] 2023-10-06 11:43
I cannot reproduce this on Ubuntu 20.04 or Debian 11. Are all the people having this issue on Linux Mint or there are other cases?

**Comment by MihaiCociuba** [comment] 2023-10-06 12:03
I had the same problem on Ubuntu Ubuntu 20.04.6 LTS (Focal Fossa), when installing from the http://ppa.launchpad.net/giuspen/ppa/ubuntu

**Comment by giuspen** [comment] 2023-10-06 12:32
Thanks for your feedback, the problem is exactly specifically with the Debian package! If I rebuild and run locally it works but if I use the PPA version it doesn't. I'll try to kick a rebuild in the PPA and if still doesn't work I'll raise a ticket on launchpad to understand what's going on

**Comment by gimplyworxs** [comment] 2023-10-06 13:29
Linux Mint 20.1 MATE has the issue, Mint 21.1 is ok (checked on a virtualbox).
Installed from PPA like the others.

**Comment by giuspen** [comment] 2023-10-06 14:26
I can now reproduce locally building the Debian package with the official scripts. Thanks for the feedback I'll get back with a fix

**Comment by gimplyworxs** [comment] 2023-10-07 07:27
Thanks very much for the quick fix.
Works as expected again

**Comment by giuspen** [comment] 2023-10-07 08:21
I pushed a new package in the Ubuntu 20.04 / focal PPA. For some reasons (likely a bug in g++ not there anymore anyway in later versions) that compiler plus specific options set from the debhelper builder messed up with a local variable used in multiple lambda functions. After I changed that variable to be non local it went away.

**Closed by giuspen** 2023-10-07 08:21 UTC
