### ISSUE TITLE
ClearType's sub-pixel rendering has changed from color to black and white, resulting in fuzzy font display

### ISSUE THREAD

**Issue by meijialun** [giuspen/cherrytree#2226] opened 2023-02-20 01:36 UTC
**Version, Operative system**
CherryTree 0.99.54, Win10 x64

**Describe the bug**
Windows ClearType's sub-pixel rendering has changed from color to black and white, resulting in fuzzy font display. And also some Chinese fonts cannot be fully displayed.

**To Reproduce**
Type some text in CherryTree 0.99.51, Windows ClearType's sub-pixel rendering looks ok.
Type some text in CherryTree 0.99.54, Windows ClearType's sub-pixel rendering has changed from color to black and white, resulting in fuzzy font display.

**Screenshots**
![51](https://user-images.githubusercontent.com/5047912/219989751-21bb002e-0cc1-4165-a849-b9c8bffc6a56.png)
![54](https://user-images.githubusercontent.com/5047912/219989774-befbb3f0-5f5b-4b21-aa1d-af67c234c715.png)

**Comment by meijialun** [comment] 2023-02-20 01:39
This problem may have existed in 0.99.52 & 53. So I haven't been able to use the new version, the font looks too bad.

**Comment by giuspen** [comment] 2023-02-21 20:43
Can you try to edit C:\Program Files\CherryTree\etc\gtk-3.0\settings.ini (or etc\gtk-3.0\settings.ini if portable) and you should have
```
[Settings]
gtk-theme-name=win32
```
Can you try and add
`gtk-xft-rgba=rgb`
(from https://docs.gtk.org/gtk4/property.Settings.gtk-xft-rgba.html - you can try any of none, rgb, bgr, vrgb, vbgr)
I'm honestly ignorant in this matter but I suspect it may be just a default GTK3 setting that changed

**Comment by meijialun** [comment] 2023-02-23 09:10
Thanks, but it seems not working, it's still gray scale.
![Snipaste_2023-02-23_14-46-29](https://user-images.githubusercontent.com/5047912/220864246-34aa3886-f7b0-47e8-b8fa-2416c1a67277.png)

**Comment by meijialun** [comment] 2023-02-24 02:26
I used your README.md method to recompile Cherrytree in Windows with MSYS2, and did not add gtk-xft-rgba=rgb configuration, the run result is OK (rgb sub-pixel rendering)
But when I use my compiled cherrytree.exe to replace with cherrytree_0.99.54_win64_portable inside, it does not work (grayscale sub-pixel rendering)
This is too strange, there may be a problem with one of the lib components

**Comment by giuspen** [comment] 2023-02-24 18:55
That's interesting.
Since you can successfully build yourself, maybe you can also try to create the portable folder yourself too, under the folder scripts it starts with msys2_...sh and generates a portable folder from your files to your Desktop.
The issue is not with the .exe but with one of the other files copied (or wrongly not copied) from the msys2 installation into the portable folder bundle (which is the same that the installer puts in Program Files)

**Comment by giuspen** [comment] 2023-02-26 20:19
Can you test https://drive.google.com/file/d/1JtGXtxgykVMYZZftTLQOf5ov-k3k_FNj/view?usp=share_link and tell me if the bug is still there?

**Comment by meijialun** [comment] 2023-02-27 02:14
I'm sorry but Google service is accessible in China. If you mean to run msys2_prepare_standalone.sh I have tried but failed like this.
![Snipaste_2023-02-27_10-13-38](https://user-images.githubusercontent.com/5047912/221456198-216cdf1a-49dd-49c1-b568-6e6d892dc999.png)
![Snipaste_2023-02-27_10-04-41](https://user-images.githubusercontent.com/5047912/221455817-34da6bbe-b279-4cdd-b5a1-8d8c6a64691e.png)
Is there some encoding problem with this folder?
![Snipaste_2023-02-27_10-07-31](https://user-images.githubusercontent.com/5047912/221455857-9f91fe93-79cf-4aeb-9589-c7aea67ec8b2.png)

**Comment by giuspen** [comment] 2023-02-27 12:57
I will try to upload the package somewhere else and get back. I shall have a look also at the failing test.

**Comment by giuspen** [comment] 2023-02-27 21:15
Do you have access to https://www.giuspen.net/software/cherrytree_0.99.54.99_win64_portable.7z ?

**Comment by meijialun** [comment] 2023-02-28 01:40
Yes, I can.
It's great, ClearType is rgb style in 0.99.54.99_win64_portable.7z now. Thanks.
[#2171](https://github.com/giuspen/cherrytree/issues/2171) is also fixed now.

**Comment by giuspen** [comment] 2023-02-28 19:55
Excellent, thank you for testing, it was an issue with a library recently fixed in msys2

**Comment by giuspen** [comment] 2023-03-07 19:27
fixed in upcoming 0.99.55

**Closed by giuspen** 2023-03-07 19:27 UTC
