### ISSUE TITLE
No autosave feature, lost a shit tonne of work

### ISSUE THREAD

**Issue by bitshiftnetau** [giuspen/cherrytree#1140] opened 2020-08-28 23:12 UTC
Please ship autosave with default ON, like literally everyone else who has an autosave feature.

**Comment by giuspen** [comment] 2020-08-29 09:25
I'm not convinced that the autosave should be on by default, personally I do save when I want with Ctrl+S so that I can just close without saving on purpose sometimes, could others cast their preference/point of view?

**Comment by bitshiftnetau** [comment] 2020-09-01 02:25
I don't think using the save feature as some kind of version control is reason to deny standard usage of autosave for users. 

Using the save feature as faux version control is something which is rather frowned upon. No offence but those are your own bad habits that shouldn't affect the community.

At the very least put up a sign on startup to say that turning it on/off is an option. 

To give you an idea why I think it's necessary: it's a standard feature nowadays, to such an extent that not only did I not think to continuously hit ctrl+s like it's 1999, but it would never have occured to me that turning on a basic feature like autosave should even be necessary. It just isn't something people do anymore and haven't for quite a while. 

However, if you really wanna keep it the way it is then at least warn people when they are closing the program that they haven't saved. That at the very least has been an industry standard courtesy for more than a decade.

Thanks for considering this option. I REALLY love the program. Kicks major ass!

**Comment by benbardon** [comment] 2020-09-01 11:34
I would not recommend this but it would be good if it save temporarily somewhere accessible

**Comment by monotok** [comment] 2020-09-01 21:44
100% agree that closing the program should prompt you to save or discard your work. Probably be a good idea to highlight the note when it has been edited but not saved, like many IDE's do. 
Upon first manual save of a note or closing without saving it could ask you if you would like auto save On or Off. That it should please everyone's preference.

**Comment by giuspen** [comment] 2020-09-02 20:59
But closing the program is definitely prompting the user to save data, if not it's a bug. What version are you running?

**Comment by monotok** [comment] 2020-09-02 21:37
Sorry my mistake. 0.99.9 definitely prompts to save when closing!

**Comment by ciranus** [comment] 2020-09-06 09:43
Warning message with 0.99.10 when trying to close a new test instance:
![2020-09-06_11-40](https://user-images.githubusercontent.com/61602511/92323081-1df95080-f036-11ea-94c8-b73db6800dad.png)

**Comment by bitshiftnetau** [comment] 2020-09-07 08:34
Apologies. Busy week. 

Windows 10 Pro Build 18363 
CherryTree v0.39.4

It is prompting for a save on quit, now that I have turned off autosave on quit. 

Garuanteed it was not doing that before when autosave on quit was not yet set. I specifically tested that before posting here or setting any options.

**Comment by ciranus** [comment] 2020-09-07 12:02
You should then clarify which exact saving settings combination you had to reproduce.
Before writing "_tonne of work_", this is the first setting I would have checked (with all applications).

![2020-09-07_13-47](https://user-images.githubusercontent.com/61602511/92385126-9b45c380-f111-11ea-8023-aedd352da7a6.png)

It's also maybe time to investigate [cherrytree_0.99.10.exe](https://www.giuspen.com/software/cherrytree_0.99.10_setup.exe)

**Comment by txe** [comment] 2020-09-07 18:39
@bitshiftnetau , there was an issue a while ago when cherrytree couldn't save changes if notes contained specific unicode symbols and just silently crashed during saving. I think it can be your case. I'm not sure if it was fixed in 0.39 (it it not under development), but it is definitely fixed in 0.99

**Comment by bitshiftnetau** [comment] 2020-09-07 21:31
Check the settings?! Yeh maybe. 

Didn't know these settings even existed and that is my point. I'm new to this app and are unaware of the settings and it is reasonable to assume I don't need to check for autosave. 

As an industry, we fixed that back in 2008.

This should not be difficult to understand friend. Users expect certain defaults when using modern programs. 

Turn it on by default on a fresh install please. If not, that's cool. I'll just use something else.

**Comment by ciranus** [comment] 2020-09-07 21:51
This is the **default** configuration I have with 0.99.10, and cannot reproduce your problem (on **Linux**).
Do you confirm you still have it with 0.99.10 on windows ? 

![2020-09-07_23-45](https://user-images.githubusercontent.com/61602511/92417818-7f1f4200-f164-11ea-80c6-17b3409b005d.png)

**Comment by metal450** [comment] 2020-09-08 20:44
> it's a standard feature nowadays, to such an extent that not only did I not think to continuously hit ctrl+s like it's 1999, but it would never have occured to me that turning on a basic feature like autosave should even be necessary. It just isn't something people do anymore and haven't for quite a while.

This is just outright false.  Ctrl+S is not "like it's 1999," and a statement like that (aside from being needlessly obnoxious) doesn't exactly seem like the best way to convince the developers to setup the software how you think it "should" be.

But hey, just out of curiosity, I'll have a quick look around my system & make sure:

MS Word+Excel+Outlook 2019 (for new emails): Nope, doesn't auto-save by default (prompts on exit or need to ctrl+s)
WPS Office (writer+spreadsheets): doesn't auto-save by default (prompts on exit or need to ctrl+s)
KWrite: doesn't auto-save by default (prompts on exit or need to ctrl+s)
Evolution (for new e-mails): doesn't auto-save by default (prompts on exit or need to ctrl+s)
Visual Studio: doesn't auto-save by default (prompts on exit or need to ctrl+s)
Foxit PhantomPDF: doesn't auto-save by default (prompts on exit or need to ctrl+s)
Photoshop: doesn't auto-save by default (prompts on exit or need to ctrl+s)
GIMP: doesn't auto-save by default (prompts on exit or need to ctrl+s)

...And so on and so on and so on.  Off the top of my head, the only software I can think of (not including mobile) that auto-saves by default is OneNote.

> Using the save feature as faux version control is something which is rather frowned upon. No offence but those are your own bad habits that shouldn't affect the community.

Again, no. I don't think you understand what "version control" is.  Choosing not to save edits is not version control.  Git is version control.  And I've never once heard of anyone "frowning upon" having the ability to control when a document saves or not.

My view is clearly the exact opposite of @bitshiftnetau: if he/she was too negligent to bother checking if it would auto-save (UNLIKE the vast majority of PC+Linux software), then it's inappropriate to come here & rail on the developers as if it were their fault.

I use the software exactly like @giuspen does and don't think it's a huge deal to expend 4 clicks or so to go into the settings & change it if the other behavior is preferred.

(Though @monotok's option of one-time asking to enable/disable autosave might be the best of both worlds.)

**Comment by funnelfiasco** [comment] 2020-09-11 16:48
I reflexively Ctrl+S every time I stop typing having after having been burned by lost work in the past. I lean toward enabling autosave by default, as I think the "I did this work but don't want to keep it" scenario is the minority use case. (Based on nothing but a hunch).

I don't feel too strongly one way or another, but it seems like autosave on best fits the "principle of least surprise" for software these days. If autosave off remains the default, I may consider overriding that in the Fedora builds.

**Comment by giuspen** [comment] 2020-09-11 17:41
I'm leaning towards enabling the autosave by default, what's your position @txe ?

**Comment by ciranus** [comment] 2020-09-11 17:59
And "autosave" has no effect if the instance has never been saved (just tested), then not helping a **new CT user** with a fresh installation.
However, my setting has always been with "autosave' (i.e. nothing against default setting).

**Comment by Peterling007** [comment] 2020-09-15 16:37
If I'm interested in a new software product, I'll look at its settings (at least briefly) before using it for a bulky job. 
And: metal450 has shown above that Autosave is not the standard behavior on similar products.
IMHO: leave the default as it is now.

**Comment by laysauchoa** [comment] 2020-09-15 19:21
I also lost a bunch of work because it did not automatically save. It would be okay if it was enable after that I kind of use another tool for notes.

**Comment by bitshiftnetau** [comment] 2020-09-28 04:10
@metal450 that is technically true, however most of those programs have a recovery feature in the case of a blackout or spontaneous shutdown. 

To be a little more exact, IF an autosave feature exists on a program it is usually enabled by default. At least, that is my experience thus far. 

I apologize for being needlessly aggressive, it is obviously inappropriate and something I am working very hard to improve. Won't happen again. 

For the record @giuspen this software is great and I am a loud advocate for it's use wherever possible. Sorry for being an asshole earlier, thanks for entertaining the suggestion.

**Comment by loansindi** [comment] 2020-10-02 02:42
Autosave should definitely be enabled by default. I've repeatedly lost work because of system restarts.

**Comment by giuspen** [comment] 2020-10-04 20:43
Also because our new young 0.99.x requires some time to stabilise I feel more comfortable in enabling by default the autosave once a minute as requested here even though I personally don't use it and disable it straight away

**Closed by giuspen** 2020-10-04 20:43 UTC
