### ISSUE TITLE
Search include node names

### ISSUE THREAD

**Issue by tom-i** [giuspen/cherrytree#1525] opened 2021-02-18 12:28 UTC
**Is your feature request related to a problem? Please describe.**
When I'm searching some string, I sometimes use different words in name of the node and inside node text.

**Describe the solution you'd like**
Would be gr8 to enhance search (Ctrl+Shift+F) to include search node names to it.

![image](https://user-images.githubusercontent.com/16342114/108356985-206af380-71ed-11eb-8218-2c2831823c23.png)

**Comment by giuspen** [comment] 2021-02-18 17:53
makes sense, I'll try and do this soon

**Comment by giuspen** [comment] 2021-09-29 21:09
this is a duplicate of https://github.com/giuspen/cherrytree/issues/513 and has been implemented, will be in the next version

**Closed by giuspen** 2021-09-29 21:09 UTC
