### ISSUE TITLE
Copy from CodeBox unformatted text results for all spaces (hex 20) utf8 non breaking spaces (hex C2A0)

### ISSUE THREAD

**Issue by Maxim4711** [giuspen/cherrytree#1938] opened 2022-01-22 13:14 UTC
**Version, Operative system**
CherryTree portable version for Windows 0.99.45 (same behaviour 0.99.44 either)
**Describe the bug**
A codebox with syntax highlighting for sh(haven't tested for other languages, probably the same), simple snippet with spaces (like "kernel.shmmni = 4096"), if the snippet is copied (right click, copy unformatted text) and pasted into terminal, then all the spaces are utf8 non breaking spaces (c2a0), obviously linux shell in terminal can not deal with
**To Reproduce**
1. Create any node
2. insert a codebox , syntax highlighting for sh, put some shell code with spaces
3. copy/paste the text from codebox as unformatted text into textfile
4. all the spaces are encoded as hex c2a0

If i remember properly, the copy/paste as unformatted text worked properly in the past (e.g. - not inserting utf8 non breaking spaces), but maybe i am wrong, i just had a codebox without any spaces within

**Comment by giuspen** [comment] 2022-01-23 20:36
I cannot reproduce, please attach a test document where I simply have to copy (as plain text?) and then tell me exactly where to paste it and how

**Comment by Maxim4711** [comment] 2022-01-24 10:40
Thanks a lot! 
Inspired by your inability to reproduce the "bug", i did some more tests and found out - non breaking spaces were already in my document by means of copy/past the code box content from a web page. Now, you probably can close this issue as a "non bug", but may i ask - would it be possible to add a possibility to convert all non printable characters to spaces (some editors e.g notepad++ have such possibility) ?

Best regards and thanks for great tool!

Maxim

**Comment by ciranus** [comment] 2022-01-24 14:52
> would it be possible to add an ability to convert within the code box all non printable characters to spaces

If you select your text, and copy/paste as **plain text**, do you still have some "_non printable characters_" (which precise definition should be 100% clarified).

**Comment by Maxim4711** [comment] 2022-01-24 19:15
Well, if the text of the code box contains nonbreaking spaces (hex C2A0) and i copy as plain text - in this case, these characters are preserved, when i paste it into linux terminal. So, in my case - the nonprintable characters are with mentioned above hex code, but i suggest, generally non printable characters doesn't make much sense within a code box (only then they are part of a string literal), the 0xC2A0 probably are quite common by copy/pasting code snippets from the web pages.
Regards

Maxim

**Comment by ciranus** [comment] 2022-01-24 19:34
A tab is commonly considered as '_non printable character_'. Is it for you ?
[What are Non-Printable Characters? - Definition from Techopedia](https://www.techopedia.com/definition/29785/non-printable-characters)
Furthermore, I don't understand how you get 0xC2A0 characters which is not a 'no-break space' for me

`슠 U+C2A0`
`HANGUL SYLLABLE SYUK`
`UTF-8 : 0xEC 0x8A 0xA0`
`UTF-16 : 0xC2A0`

` U+00A0`
`Nom : NO-BREAK SPACE, commonly abbreviated as NBSP`
`UTF-8 : 0xC2 0xA0`
`UTF-16 : 0x00A0`

**Comment by Maxim4711** [comment] 2022-01-25 10:08
[Test_1.txt](https://github.com/giuspen/cherrytree/files/7932550/Test_1.txt)
Hi, as for my needs - i'm fine with both definitions for tab, anyway - there is already builtin possibility to replace tabs with spaces, which covers probably many use cases. Regarding how i got the 0xC2A0 - i can't be sure, the attached document is where i faced this issue (if copy / past as plain text into linux terminal, e.g. putty window - i get "-bash: export ORACLE_HOSTNAME=muclx07.xyz.com: command not found", if i put (copy/paste)the character after word "export" as an argument to the od command - i get
 echo " "|od -cx
0000000 302 240  \n
           a0c2    000a

As i couldn't recreate this problem by straight typing the same content into CodeBox, my assumption was - i got it by copy/paste from some web page and probably modified the text according my needs, but for sure, i haven't touch any whitespaces, so it is probably the source of the mentioned characters

Regards
Maxim

**Comment by ciranus** [comment] 2022-01-25 10:25
I cannot reproduce this at all in linux.
You might have some windows language configuration problem somewhere. I cannot help.
Did you ask on a windows forum ?
But no doubt on 0xC2A0 which is 'HANGUL SYLLABLE SYUK'.

슠 U+C2A0
HANGUL SYLLABLE SYUK
UTF-8 : 0xEC 0x8A 0xA0
UTF-16 : 0xC2A0

**Comment by Maxim4711** [comment] 2022-01-25 10:44
Hi, just curious - you can't reproduce it with my attached example?
Regarding the resolution of the problem - i already did it in my case (means - i identified the problematic characters and replaced it with space), because i can't reproduce it in my usual workflow, i'll have to wait till i face this issue again (e.g. - copy text from web page, then copy/paste into linux terminal and get the mentioned behaviour, then i probably can be more precise regarding circumstances, how i come to this problem, but for now i'm fine. You suggestion about windows language configuration might be valid, but i can't currently think of any wrong setting.
As i mentioned earlier, this issue can be closed for now.

Regards

Maxim

**Comment by ciranus** [comment] 2022-01-25 13:32
> CherryTree portable version for **Windows** 0.99.45
... and pasted into **terminal**, then all the spaces are utf8 non breaking spaces (c2a0), obviously **linux** shell in terminal can not deal with.

Your environment seems to be your first problem to be clarified.
You have created confusion with your 'HANGUL SYLLABLE SYUK' character nobody understands for the moment where it comes from (never used / never seen).

How do you combine use of a linux terminal with a Windows CT release ?
Can you clearly tell what is your operating system ?
Which linux terminal you use ?

**Comment by Maxim4711** [comment] 2022-01-25 18:14
I don't quite understand the reason for confusion, if i was unclear at some point - please tell me what is unclear, i'll try to be more precious/go deeper in detail. 
Regarding your question - i run Windows Enterprise 10 64 bit and use CherryTree portable compiled for this OS. 
Linux terminal i mentioned - is provided by means of Putty ( https://www.putty.org/ ).
The 'HANGUL SYLLABLE SYUK'  was either not familiar to me, but after copy/paste from CT code box into Linux terminal and seeing some unexpected behavior i inspected content of what i have copy-pasted resp. analyzing the content of code box in hex viewer i have seen, the hex code 0xC2A0. 
Now i am by no means an expert in Unicode, i searched it on the internet and found https://www.scivision.dev/hex-code-c2a0-non-breaking-space-markdown/ ( and some other sites claiming the same) from which i concluded it means nbsp in utf8. Regarding your statement "nobody understands for the moment where it comes from" - it either applies to me, i don't know where it comes from, my suggestion - i have copied it from some web page as i mentioned already.

Do you need some more details / clarification from my side?

Regards

Maxim

**Comment by ciranus** [comment] 2022-01-25 18:49
I admit this is really confusing between 'Unicode' and UTF-8 and UTF-16 translated in hexa.
There is a difference for me between `0xC2A0 or 0xC2 or 0xA0` if you don't specify if this is hexa for Unicode or UTF-8 or UTF-16, but not in expert in this.
The character you will find in a webpage is not an hexa character.

Anyway, just find a web page to verify what happen in a more standard environment than yours which is very specific with 'windows/putty/linux'
Issue or not: to be clarified.

**Comment by giuspen** [comment] 2022-02-01 22:49
To be honest it could be an old version of cherrytree to be the cause of the non breaking spaces, as in the past I made use of those in the clipboard/html copy and paste, until I found a better way to preserve multiple spaces in the html.
I would implement a menu item action to replace the non breaking spaces with normal spaces if it was very common to find those in html pages with code snippets, but I believe it doesn't happen often and the command to do it already exists and is very simple:
- just select one of those non breaking space characters in the text/code
- hit Ctrl+H (replace dialog will pop up)
- in "replace with" just type a space
- hit enter

**Comment by ciranus** [comment] 2022-02-01 23:02
My opinion:
The very specific problem of Maxim4711 [windows > Putty > linux] needs to be solved with Putty configuration.
If Maxim4711 needs more than 7 days to find an example, it should not be very common, and high priority.
I don't see any reason to use NBSP instead of space in code, never seen this (code, not HTML).
When NBSP is used in HMTL, I don't see any reason to convert it as space.

Without more Maxim4711 feedback, I would close.

**Comment by giuspen** [comment] 2022-02-03 19:57
Thanks for your help @ciranus 
@Maxim4711 I'm closing as for my answer just above, just comment if you disagree.

**Closed by giuspen** 2022-02-03 19:57 UTC
