### ISSUE TITLE
Intermittent crash when adding link to text

### ISSUE THREAD

**Issue by KOM2015** [giuspen/cherrytree#35] opened 2015-05-07 13:29 UTC
For the past several versions going back at least 6 months, I've seen this intermittent crash when trying to add a link to existing text.  I type the text then highlight it, then right-click and select Insert - Insert/Edit Link.  The error happens once every day or two.

Faulting application name: cherrytree.exe, version: 0.35.7.0, time stamp: 0x49180193
Faulting module name: libgtk-win32-2.0-0.dll, version: 2.24.10.0, time stamp: 0x4f32dc49
Exception code: 0xc0000005
Fault offset: 0x001c9169
Faulting process ID: 0x29b0
Faulting application start time: 0x01d0842159431ce1
Faulting application path: C:\Users\MyUser\My Utils\CherryTree\bin\cherrytree.exe
Faulting module path: C:\Users\MyUser\My Utils\CherryTree\bin\libgtk-win32-2.0-0.dll
Report ID: 712110fc-f4bb-11e4-826d-e069955c5e5f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by giuspen** [comment] 2015-05-11 22:25
Thank you for your notification I'll see if I can reproduce the problem or
at least figure out what could be the cause

**Comment by n30m1nd** [comment] 2016-10-26 15:57
This now should be fixed with the following commits:

- https://github.com/giuspen/cherrytree/commit/52d0a1420bbee2f1ad839264e489a3c1accdb9c8
- https://github.com/giuspen/cherrytree/commit/d861245ea711f1eb68e0809a6f004daf7e476375

Attached is a PoC to reproduce the crash.
[PoC-1.zip](https://github.com/giuspen/cherrytree/files/553792/PoC-1.zip)

**Comment by txe** [comment] 2020-02-10 14:25
Looks like it is fixed

**Closed by txe** 2020-02-10 14:25 UTC
