### ISSUE TITLE
Strange list behaviour

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1327] opened 2020-11-09 18:23 UTC
**Version, Operative system**
Win 10, 0.99.19.0_win64 portable

**Describe the bug**
Trying to insert an item in an enumeration isn't possible as it was in the past (and elsewhere).

**To Reproduce**

I. Create a list, e.g:

1. first
2. second
3. third

II. set the insertion mark to just before the 2nd entry and press Enter. Now you have this:

```
1. first
second
3. third

```
Expected was that:

```
1. first
2. 
3. second
4. third

```

**Comment by txe** [comment] 2020-11-09 18:30
It is a feature, not a bug)) `Tab` allows to increase an item indent, 'Enter' - decrease.

**Comment by txe** [comment] 2020-11-09 18:34
Though, we also have `shift + Tab` which doesn't remove an item enumeration. Maybe 'Enter' also shouldn't remove it, I don't see a reason for it, what do you say, @giuspen ?

Also, I found a few bit issue with list, need to fix it ASAP ((

**Comment by giuspen** [comment] 2020-11-09 19:30
@txe we are removing the list enumerator (or also the bullet/todo) if the user presses enter with nothing in the list element, this is common behaviour with other text editors. The issue here though does not have an empty list element, I'll try to reproduce though when have access to the pc

**Comment by giuspen** [comment] 2020-11-11 23:01
this bug was also in 0.39.4, will be fixed in 0.99.20 anyway

**Closed by giuspen** 2020-11-11 23:01 UTC
